/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifAlumnos.java
 *
 * Created on 02/09/2024, 02:42:40 PM
 */
package academiafulbito.vista.interfaces;

import academiafulbito.controlador.beans.AlumnoFacade;
import academiafulbito.controlador.beans.CategoriaFacade;
import academiafulbito.controlador.beans.PadreFacade;
import academiafulbito.modelo.entidades.Alumno;
import academiafulbito.modelo.entidades.Categoria;
import academiafulbito.modelo.enums.Estado;
import academiafulbito.vista.utilidades.DialogUtils;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import java.text.ParseException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter Jair
 */
public class jifAlumnos extends javax.swing.JInternalFrame {

    JDesktopPane jdp;
    public static AlumnoFacade alumnoFacade;
    public static CategoriaFacade categoriaFacade;
    public static PadreFacade padreFacade;
    
    DefaultTableModel modelo;
    String[] nombreColumnas = {
        LiteralesTexto.LITERAL_ID,
        LiteralesTexto.LITERAL_NOMBRE,
        LiteralesTexto.LITERAL_APELLIDO,
        LiteralesTexto.LITERAL_FECHA_NACIMIENTO,
        LiteralesTexto.LITERAL_ID,//4 categoria
        LiteralesTexto.LITERAL_NOMBRE,//5 nombre categoria
        LiteralesTexto.LITERAL_ID, //6 idpadre
        LiteralesTexto.LITERAL_NOMBRE,//7 nombre padre
        LiteralesTexto.LITERAL_APELLIDO, // 8 apellido padre
        LiteralesTexto.LITERAL_ESTADO, //9 estado
        LiteralesTexto.LITERAL_DNI, //10 dni alumno
        LiteralesTexto.LITERAL_VER,
        LiteralesTexto.LITERAL_EDITAR,
        LiteralesTexto.LITERAL_ELIMINAR
    };
    int indicador;//para saber si estamos en modo de edicion

    private int idSeleccionada; // Variable para almacenar la ID del alumno seleccionado
    private int paginaActual = 1;
    private int tamanioPagina = 5;//para el paginado de tabla
    private int totalPaginas;

    jifCategorias menuCategorias;
    jifPadres menuPadres;

    /** Creates new form jifAlumnos */
    public jifAlumnos(JDesktopPane jdpModAF) {
        initComponents();
        jdp = jdpModAF;
        Utils.cargarComboEstado(jcbEstado);
        categoriaFacade=new CategoriaFacade();
        padreFacade=new PadreFacade();
        alumnoFacade=new AlumnoFacade();

        accionBotones(false, false);
        alumnoFacade = new AlumnoFacade();
        listarAlumnos(paginaActual, tamanioPagina);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tphAlumnos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspPadres = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnNuevoAlumno = new org.edisoncor.gui.button.ButtonRound();
        btnAnterior = new org.edisoncor.gui.button.ButtonRound();
        lblPaginaActual = new javax.swing.JLabel();
        btnSiguiente = new org.edisoncor.gui.button.ButtonRound();
        jPanel2 = new javax.swing.JPanel();
        txtApellido = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdPadre = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnGuardar = new org.edisoncor.gui.button.ButtonRound();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jcbEstado = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePadre = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdCategoria = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtNombreCategoria = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarPadre = new javax.swing.JButton();
        btnBuscarCategoria = new javax.swing.JButton();
        jdcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new org.edisoncor.gui.textField.TextFieldRoundBackground();

        setBackground(new java.awt.Color(135, 135, 246));
        setClosable(true);
        setTitle("MANTENIMIENTO ALUMNOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphAlumnos.setFont(new java.awt.Font("Bookman Old Style", 1, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspPadres.setBackground(new java.awt.Color(255, 255, 255));
        jspPadres.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspPadres.setOpaque(false);

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAlumnos.setOpaque(false);
        jspPadres.setViewportView(tblAlumnos);

        jPanel1.add(jspPadres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 220));

        btnNuevoAlumno.setBackground(new java.awt.Color(156, 156, 247));
        btnNuevoAlumno.setText("+ ALUMNOS");
        btnNuevoAlumno.setFont(new java.awt.Font("Arial", 1, 18));
        btnNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 50));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior.setText("<<");
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 24));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, 50));

        lblPaginaActual.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        lblPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaginaActual.setText("10");
        jPanel1.add(lblPaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 220, 50));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText(">>");
        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 24));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, 50));

        tphAlumnos.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido.setEditable(false);
        txtApellido.setDescripcion("Apellidos*");
        txtApellido.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 720, 40));

        txtIdPadre.setEditable(false);
        txtIdPadre.setDescripcion("ID*");
        txtIdPadre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtIdPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, 40));

        btnGuardar.setBackground(new java.awt.Color(156, 156, 247));
        btnGuardar.setBorder(null);
        btnGuardar.setText("AÑADIR");
        btnGuardar.setBorderPainted(true);
        btnGuardar.setContentAreaFilled(true);
        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 170, 70));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO ALUMNO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 250, 20));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 220, 70));

        jcbEstado.setEnabled(false);
        jcbEstado.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("ESTADO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 170, 40));

        txtNombrePadre.setEditable(false);
        txtNombrePadre.setDescripcion("Nombre Padre*");
        txtNombrePadre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtNombrePadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 340, 40));

        txtIdCategoria.setEditable(false);
        txtIdCategoria.setDescripcion("ID*");
        txtIdCategoria.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 40));

        txtNombreCategoria.setEditable(false);
        txtNombreCategoria.setDescripcion("Nombre Categoria*");
        txtNombreCategoria.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 340, 40));

        txtNombre.setEditable(false);
        txtNombre.setDescripcion("Nombre*");
        txtNombre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 720, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("FECHA DE NACIMIENTO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 180, 40));

        btnBuscarPadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/buscar.png"))); // NOI18N
        btnBuscarPadre.setContentAreaFilled(false);
        btnBuscarPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPadreActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 60, 50));

        btnBuscarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/buscar.png"))); // NOI18N
        btnBuscarCategoria.setContentAreaFilled(false);
        btnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 50, 50));
        jPanel2.add(jdcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 230, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("DATOS DEL PADRE DEL ALUMNO:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 240, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("DATOS DE LA CATEGORIA QUE PERTENECE:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 320, 30));

        txtDni.setEditable(false);
        txtDni.setDescripcion("DNI Alumno*");
        txtDni.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 300, 40));

        tphAlumnos.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlumnoActionPerformed
        // TODO add your handling code here:
        indicador = 0;//para poder guardar
        tphAlumnos.setSelectedIndex(1);
        limpiarCampos();
        habilitarCampos(true);
        accionBotones(true, true);
    }//GEN-LAST:event_btnNuevoAlumnoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (validarDatosCategoria()) {
                String cadenaMensaje = 0 == indicador ? LiteralesTexto.ESTA_SEGURO_GUARDAR_NUEVO_REGISTRO : LiteralesTexto.ESTA_SEGURO_MODIFICAR_REGISTRO;
                if (Utils.mensajeConfirmacion(cadenaMensaje) == JOptionPane.YES_OPTION) {
                    Alumno alumno;
                    switch (indicador) {
                        case 0: // Registrar alumno
                            alumno = new Alumno();
                            alumno = getDatosAlumno(alumno); // Obtener los datos del alumno
                            if (alumno != null) {
                                alumnoFacade.guardarAlumno(alumno);
                                Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                            }
                            break;
                        /*case 0://registrar alumno
                        alumno = new Alumno();
                        alumnoFacade.guardarAlumno(getDatosAlumno(alumno));
                        Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                        break;*/
                        case 1://actualizar alumno
                            alumno = alumnoFacade.findAlumnoById(idSeleccionada);
                            alumnoFacade.actualizarAlumno(getDatosAlumno(alumno));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_ACTUALIZADO_CORRECTAMENTE);
                            break;
                    }

                    listarAlumnos(paginaActual, tamanioPagina);
                    limpiarCampos();
                    habilitarCampos(false);
                    accionBotones(false, false);
                    btnGuardar.setText("Añadir");
                    indicador = 0;
                    tphAlumnos.setSelectedIndex(0);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        habilitarCampos(false);
        tphAlumnos.setSelectedIndex(0);
        accionBotones(false,false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            listarAlumnos(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
           listarAlumnos(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCategoriaActionPerformed
        // TODO add your handling code here:
        if (jfPrincipal.menuCategorias == null || jfPrincipal.menuCategorias.isClosed()) {
            jfPrincipal.menuCategorias = new jifCategorias(jdp); // Instanciamos la ventana de Categorías
            // Llamamos al método para gestionar la visualización
            Utils.visualizarInternalFrame(jfPrincipal.menuCategorias, jdp);
        }
        jfPrincipal.menuCategorias.permiteSelFila=0;//este valor permite seleccionar con un clic en la fila de la tabla de categorias
        jfPrincipal.menuCategorias.toFront(); // Traer al frente
    }//GEN-LAST:event_btnBuscarCategoriaActionPerformed

    private void btnBuscarPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPadreActionPerformed
        // TODO add your handling code here:
        if(jfPrincipal.menuPadres == null || jfPrincipal.menuPadres.isClosed()){
            jfPrincipal.menuPadres = new jifPadres(jdp);
            Utils.visualizarInternalFrame(jfPrincipal.menuPadres, jdp);
        }
        jfPrincipal.menuPadres.permiteSelFila=0;//este valor permite seleccionar con un clic en la fila de la tabla de padres
        jfPrincipal.menuPadres.toFront();
    }//GEN-LAST:event_btnBuscarPadreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ' && c != evt.VK_BACK_SPACE) {
            evt.consume(); // Consume el evento si no es letra ni espacio
        }
        evt.setKeyChar(Character.toUpperCase(c)); // Convertir a mayúsculas
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ' && c != evt.VK_BACK_SPACE) {
            evt.consume(); // Consume el evento si no es letra ni espacio
        }
        evt.setKeyChar(Character.toUpperCase(c)); // Convertir a mayúsculas
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Permitir solo dígitos y hasta 2 caracteres
        if (!Character.isDigit(c) || txtDni.getText().length() >= 12) {
            evt.consume(); // Ignorar el evento de tecla
        }
    }//GEN-LAST:event_txtDniKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnAnterior;
    private javax.swing.JButton btnBuscarCategoria;
    private javax.swing.JButton btnBuscarPadre;
    private javax.swing.JButton btnCancelar;
    private org.edisoncor.gui.button.ButtonRound btnGuardar;
    private org.edisoncor.gui.button.ButtonRound btnNuevoAlumno;
    private org.edisoncor.gui.button.ButtonRound btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.comboBox.ComboBoxRound jcbEstado;
    private com.toedter.calendar.JDateChooser jdcFechaNacimiento;
    private javax.swing.JScrollPane jspPadres;
    private javax.swing.JLabel lblPaginaActual;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTabbedPane tphAlumnos;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtApellido;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtDni;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdCategoria;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdPadre;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtNombre;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtNombreCategoria;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtNombrePadre;
    // End of variables declaration//GEN-END:variables

   private void listarAlumnos(List<Alumno> listaAlumnos) {
         // Selecciona el primer tab en un JTabbedPane
        tphAlumnos.setSelectedIndex(0);

        modelo = Utils.generarModeloTabla(nombreColumnas);

        // Asignar el modelo a la tabla
        tblAlumnos.setModel(modelo);

        int[] anchoColumnas = {35, 60, 45, 20, 20, 20,20,20,20,20, 20,15, 15, 15}; // Anchos específicos para cada columna
        Utils.setAnchoColumnas(tblAlumnos, anchoColumnas);
        Utils.ocultarColumnas(tblAlumnos, 0);//ocultar la primera columna
        Utils.ocultarColumnas(tblAlumnos, 4);//ocultar columna idCategoria
        Utils.ocultarColumnas(tblAlumnos, 5);//ocultar columna NombreCategoria
        Utils.ocultarColumnas(tblAlumnos, 6);//ocultar columna idPadre
        Utils.ocultarColumnas(tblAlumnos, 7);//ocultar columna NombrePadre
        Utils.ocultarColumnas(tblAlumnos, 8);//ocultar columna ApellidoPadre
        Utils.ocultarColumnas(tblAlumnos, 9);//ocultar columna estado
        

        // limpia los datos existentes en la tabla.
        Utils.limpiarModeloTabla(modelo, tblAlumnos);

        // Verificar si la lista tiene elementos
        if (listaAlumnos.size() > 0) {
            // Iterar sobre la lista y agregar cada objeto a la tabla
            for (Alumno alumno : listaAlumnos) {

                // Crea un array de objetos con los datos del objeto para agregar a la tabla.
                Object[] fila = new Object[]{
                    alumno.getIdAlumno(),//0
                    alumno.getNombreAlumno(),//1
                    alumno.getApellidoAlumno(),//2
                    Utils.getFechaFormateada(alumno.getFechaNacimiento()),//3
                    alumno.getCategoria().getIdCategoria(),//4
                    alumno.getCategoria().getNombre(),//5
                    alumno.getPadre().getIdPadre(),//6
                    alumno.getPadre().getNombrePadre(),//7
                    alumno.getPadre().getApellidoPadre(),//8
                    alumno.getEstado(),//9
                    alumno.getDniAlumno(),//10
                    LiteralesTexto.LITERAL_VER,//11
                    LiteralesTexto.LITERAL_EDITAR,//12
                    LiteralesTexto.LITERAL_ELIMINAR//13
                };
                modelo.addRow(fila); // Agregar la fila al modelo de la tabla
            }
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblAlumnos.setDefaultRenderer(Object.class, new Utils(18));


            Utils.configurarEstiloTabla(tblAlumnos, jspPadres);
            Utils.configurarBotonesAccion(tblAlumnos);

        }
    }

   private Alumno getDatosAlumno(Alumno alumno) {

        alumno.setNombreAlumno(txtNombre.getText());
        alumno.setApellidoAlumno(txtApellido.getText());
        alumno.setFechaNacimiento(jdcFechaNacimiento.getDate());
        int categoria = Integer.parseInt(txtIdCategoria.getText());
        alumno.setCategoria(categoriaFacade.findCategoriaById(categoria));
        int padre = Integer.parseInt(txtIdPadre.getText());
        alumno.setPadre(padreFacade.findPadreById(padre));
        alumno.setEstado((Estado) jcbEstado.getSelectedItem());
        alumno.setDniAlumno(txtDni.getText());

        return alumno;

    }

    private void limpiarCampos() {
        txtNombre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtApellido.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        jdcFechaNacimiento.setDate(null);
        txtIdCategoria.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombreCategoria.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtIdPadre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombrePadre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtDni.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void habilitarCampos(boolean band) {
        txtNombre.setEditable(band);
        txtApellido.setEditable(band);
        jdcFechaNacimiento.setEnabled(band);
        if (indicador == 0) {
            jcbEstado.setSelectedIndex(0);
            jcbEstado.setEnabled(!band);
        } else {
            jcbEstado.setEnabled(band);
        }
        txtDni.setEditable(band);
    }

    private void accionBotones(boolean d, boolean e) {
        btnCancelar.setEnabled(d);
        btnGuardar.setEnabled(e);
    }

    public void cargarDatosEnFormulario(int row) throws ParseException {
        if (row != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblAlumnos.getValueAt(row, 0).toString()); // Supone que la ID está en la primera columna

            // Obtener los datos de la fila seleccionada
            String nombre = (String) tblAlumnos.getValueAt(row, 1);
            String apellido = (String) tblAlumnos.getValueAt(row, 2);
            String fechaNacimiento= (String) tblAlumnos.getValueAt(row, 3);
            int idCategoria= Integer.parseInt(tblAlumnos.getValueAt(row, 4).toString());
            String nombreCategoria=(String) tblAlumnos.getValueAt(row, 5);
            int idPadre= Integer.parseInt(tblAlumnos.getValueAt(row, 6).toString());
            String nombrePadre=(String) tblAlumnos.getValueAt(row, 7);
            String apellidoPadre=(String) tblAlumnos.getValueAt(row, 8);
            Estado estado = (Estado) tblAlumnos.getValueAt(row, 9);
            String dniAlumno=(String) tblAlumnos.getValueAt(row, 10);

            // Asignar los datos a los JTextField en el segundo panel
            txtNombre.setText(nombre);
            txtApellido.setText(apellido);
            jdcFechaNacimiento.setDate(Utils.getDate(fechaNacimiento));
            txtIdCategoria.setText(""+idCategoria);
            txtNombreCategoria.setText(nombreCategoria);
            txtIdPadre.setText(""+idPadre);
            txtNombrePadre.setText(nombrePadre+" "+apellidoPadre);
            txtDni.setText(dniAlumno);


            // Seleccionar el estado en el JComboBox
            jcbEstado.setSelectedItem(estado);

            // Cambiar al segundo panel donde están los JTextField
            tphAlumnos.setSelectedIndex(1);
            btnGuardar.setText("Modificar");
            indicador = 1;
            accionBotones(true, true);
            habilitarCampos(true);
        } else {
            //colocar alguna alerta
        }
    }

    private void listarAlumnos(int paginaActual, int tamanioPagina) {
        totalPaginas = alumnoFacade.obtenerTotalPaginas(tamanioPagina);

        List<Alumno> listaalumnos = alumnoFacade.listarEntidadesPaginadas(paginaActual, tamanioPagina);

        // Actualizar el JLabel con la página actual
        lblPaginaActual.setText("Página " + paginaActual + " de " + totalPaginas);

        // Mostrar las categorías en la tabla
        listarAlumnos(listaalumnos);
        actualizarEstadoBotones();// Actualizar el estado de los botones
    }

    private void actualizarEstadoBotones() {
        btnAnterior.setEnabled(paginaActual > 1);
        btnSiguiente.setEnabled(paginaActual < totalPaginas);
    }

    public void eliminarAlumnoSeleccionada(int filaSeleccionada) {
        if (filaSeleccionada != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblAlumnos.getValueAt(filaSeleccionada, 0).toString()); // Supone que la ID está en la primera columna
            if (Utils.mensajeConfirmacion(LiteralesTexto.ESTA_SEGURO_ELIMINAR_REGISTRO) == JOptionPane.YES_OPTION) {
                Alumno alumnoAEliminar = alumnoFacade.findAlumnoById(idSeleccionada);
                if(alumnoAEliminar != null){
                    try {
                        // Llamar al método para eliminar
                        alumnoFacade.eliminarAlumno(alumnoAEliminar);
                        JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_ELIMINADO_CORRECTAMENTE);

                        // Actualizar la tabla después de eliminar
                        totalPaginas = alumnoFacade.obtenerTotalPaginas(tamanioPagina);

                        // Verificar si la página actual es mayor que el total de páginas después de la eliminación
                        if (paginaActual > totalPaginas) {
                            paginaActual = totalPaginas; // Ajustar la página actual a la última disponible
                        }

                        // Actualizar la tabla después de eliminar
                        listarAlumnos(paginaActual, tamanioPagina); // Volver a listar los padres después de la eliminación

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, LiteralesTexto.ERROR_AL_ELIMINAR_EL_REGISTRO+ " : " + e.getMessage(), LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_NO_ENCONTRADO_EN_LA_BBDD, LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                }

            }
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, LiteralesTexto.POR_FAVOR_SELECCIONE_UNA_REGISTRO_PARA_ELIMINAR);
        }
    }

    public void mostrarInformacionAlumno(int filaSeleccionada) {

        // Supongamos que tienes un modelo de tabla que almacena los datos.
        String nombreAlumno = (String) tblAlumnos.getValueAt(filaSeleccionada, 1); // Ajusta el índice de columna según tu tabla
        String apellidoAlumno = (String) tblAlumnos.getValueAt(filaSeleccionada, 2);
        String fechaNacimiento= (String) tblAlumnos.getValueAt(filaSeleccionada, 3);
        String nombreCategoria = (String) tblAlumnos.getValueAt(filaSeleccionada, 5);
        String nombrePadre = (String) tblAlumnos.getValueAt(filaSeleccionada, 7);
        String apellidoPadre = (String) tblAlumnos.getValueAt(filaSeleccionada, 8);
        Estado estado = (Estado)tblAlumnos.getValueAt(filaSeleccionada, 9);
        String dniAlunno = (String) tblAlumnos.getValueAt(filaSeleccionada, 10);


        // Crear un mapa con los datos a mostrar
        //Map<String, String> datos = new HashMap<String, String>(5);
        Map<String, String> datos = new LinkedHashMap<String, String>(5);
        datos.put("Nombre Alumno :", nombreAlumno);
        datos.put("Apellido Alumno :",apellidoAlumno);
        datos.put("Fec. Nac. Alumno :",fechaNacimiento);
        datos.put("DNI Alumno :",dniAlunno);
        datos.put("Categoria que pertenece :", nombreCategoria);
        datos.put("Datos del Padre :", nombrePadre+" "+apellidoPadre);
        datos.put("Estado:", estado.toString());
        

        // Llamar al método genérico para mostrar la información
        //primer parametro: nombre de tu boton, cuarto parametro: tamaño letra y ultimo parametro es la longitud de la cadena
        DialogUtils.mostrarInformacion("Aceptar","INFORMACIÓN DEL ALUMNO", datos, 18, 20);
    }

     private boolean validarDatosCategoria() {
        if (!validarCampo(txtNombre.getText(), LiteralesTexto.ERROR_NOMBRE_CAMPO_VACIO)) {
            return false;
        }

        if (!validarCampo(txtApellido.getText(), LiteralesTexto.ERROR_APELLIDO_CAMPO_VACIO)) {
            return false;
        }

        if (!validarCampo(txtDni.getText(), LiteralesTexto.ERROR_DNI_CAMPO_VACIO)) {
            return false;
        }

        if (jdcFechaNacimiento.getDate() == null) {
            Utils.mensajeError(LiteralesTexto.ERROR_FECHA_CAMPO_VACIO);
            return false;
        }

        if (!validarCampo(txtIdCategoria.getText(), LiteralesTexto.ERROR_ID_CAMPO_VACIO)) {
            return false;
        }

        if (!validarCampo(txtIdPadre.getText(), LiteralesTexto.ERROR_ID_CAMPO_VACIO)) {
            return false;
        }
        
        return true;
    }

    private boolean validarCampo(String valor, String mensajeError) {
        if (!Utils.validarCadena(valor)) {
            Utils.mensajeError(mensajeError);
            return false;
        }
        return true;
    }
}
