/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCategorias.java
 *
 * Created on 02/08/2024, 02:42:40 PM
 */

package academiafulbito.vista.interfaces;

import academiafulbito.controlador.beans.CategoriaFacade;
import academiafulbito.controlador.beans.CategoriaProductoFacade;
import academiafulbito.modelo.entidades.Categoria;
import academiafulbito.modelo.entidades.CategoriaProducto;
import academiafulbito.modelo.enums.Estado;
import academiafulbito.vista.reportes.Reportes;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import java.awt.Cursor;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter Jair
 */
public class jifCategoriaProducto extends javax.swing.JInternalFrame {

    JDesktopPane jdp;
    public static CategoriaProductoFacade categoriaProductoFacade;
    public static int permiteSelFila = -1;//este valor no permite seleccionar la fila en la tabla
    DefaultTableModel modelo;
    String[] nombreColumnas = {
        LiteralesTexto.LITERAL_ID,//0
        LiteralesTexto.LITERAL_NOMBRE, //1
        LiteralesTexto.LITERAL_DESCRIPCION, //2
        //LiteralesTexto.LITERAL_EDAD_MAX,
        LiteralesTexto.LITERAL_ESTADO, //3
        LiteralesTexto.LITERAL_VER, //4
        LiteralesTexto.LITERAL_EDITAR, //5
        LiteralesTexto.LITERAL_ELIMINAR //6
    };
    int indicador;//para saber si estamos en modo de edicion
    private int idSeleccionada; // Variable para almacenar la ID de la categoría seleccionada
    private int paginaActual = 1;
    private int tamanioPagina = 5;//para el paginado de tabla
    private int totalPaginas;
    /** Creates new form jifCategorias */
    public jifCategoriaProducto(JDesktopPane jdpModAF){
        initComponents();
        jdp=jdpModAF;
        Utils.cargarComboEstado(jcbEstado);
        accionBotones(false, false, false);
        categoriaProductoFacade = new CategoriaProductoFacade();
        listarCategorias(paginaActual, tamanioPagina);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tphCategoriaProducto = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspCategorias = new javax.swing.JScrollPane();
        tblCategoriaProducto = new javax.swing.JTable();
        lblPaginaActual = new javax.swing.JLabel();
        btnAnterior = new org.edisoncor.gui.button.ButtonRound();
        btnSiguiente = new org.edisoncor.gui.button.ButtonRound();
        btnRepAlumnosPorCateg = new javax.swing.JButton();
        btnNuevaCategoria = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtDescripcion = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtIdCategoria = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jcbEstado = new org.edisoncor.gui.comboBox.ComboBoxRound();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setTitle("MANTENIMIENTO CATEGORIA PRODUCTO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphCategoriaProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspCategorias.setBackground(new java.awt.Color(255, 255, 255));
        jspCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspCategorias.setOpaque(false);

        tblCategoriaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCategoriaProducto.setOpaque(false);
        tblCategoriaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriaProductoMouseClicked(evt);
            }
        });
        tblCategoriaProducto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblCategoriaProductoMouseMoved(evt);
            }
        });
        jspCategorias.setViewportView(tblCategoriaProducto);

        jPanel1.add(jspCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1130, 280));

        lblPaginaActual.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        lblPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaginaActual.setText("10");
        jPanel1.add(lblPaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 220, 50));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior.setText("<<");
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 24));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, 50));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText(">>");
        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 24));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 420, -1, 50));

        btnRepAlumnosPorCateg.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnRepAlumnosPorCateg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/imprimir-pdf.png"))); // NOI18N
        btnRepAlumnosPorCateg.setText("<html><center>ALUMNOS POR<br> CATEGORIA</center></html>");
        btnRepAlumnosPorCateg.setToolTipText("Visualiza reporte de alumnos por categoria");
        btnRepAlumnosPorCateg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRepAlumnosPorCateg.setContentAreaFilled(false);
        btnRepAlumnosPorCateg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRepAlumnosPorCateg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRepAlumnosPorCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepAlumnosPorCategActionPerformed(evt);
            }
        });
        jPanel1.add(btnRepAlumnosPorCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 170, 120));

        btnNuevaCategoria.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnNuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/nuevo.png"))); // NOI18N
        btnNuevaCategoria.setText("<html><center>NUEVA<br>CATEGORIA</center></html>");
        btnNuevaCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNuevaCategoria.setContentAreaFilled(false);
        btnNuevaCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 160, 120));

        tphCategoriaProducto.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setEditable(false);
        txtNombre.setDescripcion("Nombre*");
        txtNombre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 720, 40));

        txtDescripcion.setEditable(false);
        txtDescripcion.setDescripcion("Descripcion*");
        txtDescripcion.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 720, 40));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLabel1.setForeground(new java.awt.Color(103, 98, 98));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVA CATEGORIA PRODUCTO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 500, 20));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 190, 80));
        jPanel2.add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 40));
        txtIdCategoria.setVisible(false);

        btnImprimir.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/reportes.png"))); // NOI18N
        btnImprimir.setText("REPORTE");
        btnImprimir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 190, 80));

        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/guardar-datos.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 190, 80));

        jcbEstado.setEnabled(false);
        jcbEstado.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 220, 40));

        tphCategoriaProducto.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        habilitarCampos(false);
        tphCategoriaProducto.setSelectedIndex(0);
        accionBotones(false, false, false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
            listarCategorias(paginaActual, tamanioPagina);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            //listarCategorias(Utils.cargarPaginado(paginaActual, tamanioPagina, lblPaginaActual, jfPrincipal.menuCategorias));
            listarCategorias(paginaActual, tamanioPagina);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(c)); // Convertir a mayúsculas
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(c)); // Convertir a mayúsculas
    }//GEN-LAST:event_txtNombreKeyTyped

    private void tblCategoriaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaProductoMouseClicked
        // TODO add your handling code here:
        int nroFila = tblCategoriaProducto.getSelectedRow();
        if (nroFila != -1) {
            switch (permiteSelFila) {
                case 0://permite llamarlo desde una ventana externa
                    jfPrincipal.menuProductoServicios.txtIdCategoriaProducto.setText(tblCategoriaProducto.getValueAt(nroFila, 0).toString());
                    jfPrincipal.menuProductoServicios.txtCategoriaProducto.setText(tblCategoriaProducto.getValueAt(nroFila, 1).toString());
                    break;
                case 1://permite llamarlo desde una ventana externa
                    jfPrincipal.menuProductoServicios.txtIdCategoriaProducto.setText(tblCategoriaProducto.getValueAt(nroFila, 0).toString());
                    jfPrincipal.menuProductoServicios.txtCategoriaProducto.setText(tblCategoriaProducto.getValueAt(nroFila, 1).toString());
                    break;
            }
            //cerrar ventana
            try {
                setClosed(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_tblCategoriaProductoMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        Map parametros = new HashMap();
        parametros.put("idCategoria", txtIdCategoria.getText()); // Ejemplo de parámetro para el reporte
        // Llamar al método para generar y mostrar el reporte
        Reportes.imprimirReporte(parametros, "rp_categoria.jasper");
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnRepAlumnosPorCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepAlumnosPorCategActionPerformed
        // TODO add your handling code here:
        // Definir los parámetros necesarios para el reporte
        Map parametros = new HashMap();
        // Llamar al método para generar y mostrar el reporte
        Reportes.imprimirReporte(parametros, "rp_alumnos_por_categoria.jasper");
}//GEN-LAST:event_btnRepAlumnosPorCategActionPerformed

    private void btnNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCategoriaActionPerformed
        // TODO add your handling code here:
        indicador = 0;//para poder guardar
        tphCategoriaProducto.setSelectedIndex(1);
        limpiarCampos();
        habilitarCampos(true);
        accionBotones(true, true,false);
    }//GEN-LAST:event_btnNuevaCategoriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (validarDatosCategoria()) {
                String cadenaMensaje = 0 == indicador ? LiteralesTexto.ESTA_SEGURO_GUARDAR_NUEVO_REGISTRO : LiteralesTexto.ESTA_SEGURO_MODIFICAR_REGISTRO;
                if (Utils.mensajeConfirmacion(cadenaMensaje) == JOptionPane.YES_OPTION) {
                    CategoriaProducto categoriaProducto;
                    switch (indicador) {
                        case 0://registrar categoria
                            categoriaProducto = new CategoriaProducto();
                            categoriaProductoFacade.guardarCategoriaProducto(getDatosCategoria(categoriaProducto));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                            break;
                        case 1://actualizar categoria
                            categoriaProducto = categoriaProductoFacade.findCategoriaProductoById(idSeleccionada);
                            categoriaProductoFacade.actualizarCategoria(getDatosCategoria(categoriaProducto));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_ACTUALIZADO_CORRECTAMENTE);
                            break;
                    }

                    listarCategorias(paginaActual, tamanioPagina);
                    limpiarCampos();
                    habilitarCampos(false);
                    accionBotones(false, false, false);
                    btnGuardar.setText("Añadir");
                    indicador = 0;
                    tphCategoriaProducto.setSelectedIndex(0);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblCategoriaProductoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaProductoMouseMoved
        // TODO add your handling code here:
        int col = tblCategoriaProducto.columnAtPoint(evt.getPoint());
        int row = tblCategoriaProducto.rowAtPoint(evt.getPoint());
        if (col >= 0 && (tblCategoriaProducto.getColumnName(col).equals(LiteralesTexto.LITERAL_VER) ||
                         tblCategoriaProducto.getColumnName(col).equals(LiteralesTexto.LITERAL_EDITAR) ||
                         tblCategoriaProducto.getColumnName(col).equals(LiteralesTexto.LITERAL_ELIMINAR))) {
            tblCategoriaProducto.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            tblCategoriaProducto.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_tblCategoriaProductoMouseMoved




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevaCategoria;
    private javax.swing.JButton btnRepAlumnosPorCateg;
    private org.edisoncor.gui.button.ButtonRound btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.comboBox.ComboBoxRound jcbEstado;
    private javax.swing.JScrollPane jspCategorias;
    private javax.swing.JLabel lblPaginaActual;
    public static javax.swing.JTable tblCategoriaProducto;
    private javax.swing.JTabbedPane tphCategoriaProducto;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtDescripcion;
    private javax.swing.JTextField txtIdCategoria;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtNombre;
    // End of variables declaration//GEN-END:variables

    private void listarCategoriaProducto(List<CategoriaProducto> listaCategoriaProducto){
        // Selecciona el primer tab en un JTabbedPane
        tphCategoriaProducto.setSelectedIndex(0);
        
        modelo = Utils.generarModeloTabla(nombreColumnas);

        // Asignar el modelo a la tabla
        tblCategoriaProducto.setModel(modelo);

        int[] anchoColumnas = {15, 60, 20, 20, 15, 25, 25}; // Anchos específicos para cada columna
        Utils.setAnchoColumnas(tblCategoriaProducto, anchoColumnas);
        Utils.ocultarColumnas(tblCategoriaProducto, 0);//ocultar la primera columna
        Utils.ocultarColumnas(tblCategoriaProducto, 3);//ocultar columna estado
        
        // limpia los datos existentes en la tabla.
        Utils.limpiarModeloTabla(modelo, tblCategoriaProducto);

        // Verificar si la lista tiene elementos
        if (listaCategoriaProducto.size() > 0) {
            // Iterar sobre la lista y agregar cada objeto a la tabla
            for (CategoriaProducto categoriaProducto : listaCategoriaProducto) {

                // Crea un array de objetos con los datos del objeto para agregar a la tabla.
                Object[] fila = new Object[]{
                    categoriaProducto.getIdCategoriaProd(),
                    categoriaProducto.getNombreCategoria(),
                    categoriaProducto.getDescripcion(),
                    categoriaProducto.getEstado(),
                    LiteralesTexto.LITERAL_VER,
                    LiteralesTexto.LITERAL_EDITAR,
                    LiteralesTexto.LITERAL_ELIMINAR
                };
                modelo.addRow(fila); // Agregar la fila al modelo de la tabla
            }
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblCategoriaProducto.setDefaultRenderer(Object.class, new Utils(14));
            
            Utils.configurarEstiloTabla(tblCategoriaProducto, jspCategorias);
            Utils.configurarBotonesAccion(tblCategoriaProducto);
        }
    }

    private CategoriaProducto getDatosCategoria(CategoriaProducto categoriaProducto){
        categoriaProducto.setNombreCategoria(txtNombre.getText());
        categoriaProducto.setDescripcion(txtDescripcion.getText());
        
        categoriaProducto.setEstado((Estado)jcbEstado.getSelectedItem());

        return categoriaProducto;
    }

    private void limpiarCampos() {
        txtNombre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtDescripcion.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        
    }

    private void habilitarCampos(boolean band){
        txtNombre.setEditable(band);
        txtDescripcion.setEditable(band);
        
        if(indicador == 0){
            jcbEstado.setSelectedIndex(0);
            jcbEstado.setEnabled(!band);
        } else{
            jcbEstado.setEnabled(band);
        }
        
    }

    private void accionBotones(boolean d, boolean e, boolean f) {
        btnCancelar.setEnabled(d);
        btnGuardar.setEnabled(e);
        btnImprimir.setEnabled(f);
    }

    public void cargarDatosEnFormulario(int row) {
        if (row != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblCategoriaProducto.getValueAt(row, 0).toString()); // Supone que la ID está en la primera columna

            // Obtener los datos de la fila seleccionada
            String nombre = (String) tblCategoriaProducto.getValueAt(row, 1);
            String descripcion = (String) tblCategoriaProducto.getValueAt(row, 2);
            Estado estado = (Estado) tblCategoriaProducto.getValueAt(row, 3);


            // Asignar los datos a los JTextField en el segundo panel
            txtNombre.setText(nombre);//11
            txtDescripcion.setText(descripcion);//2

            // Seleccionar el estado en el JComboBox
            jcbEstado.setSelectedItem(estado);//3

            // Cambiar al segundo panel donde están los JTextField
            tphCategoriaProducto.setSelectedIndex(1);
            btnGuardar.setText("Modificar");
            indicador = 1;
            accionBotones(true, true, true);
            habilitarCampos(true);
        } else {
            //colocar alguna alerta
        }
    }

    private void listarCategorias(int paginaActual, int tamanioPagina) {
        totalPaginas = categoriaProductoFacade.obtenerTotalPaginas(tamanioPagina);

        List<CategoriaProducto> listaCategoriaProductos = categoriaProductoFacade.listarEntidadesPaginadas(paginaActual, tamanioPagina);

        // Actualizar el JLabel con la página actual
        lblPaginaActual.setText("Página " + paginaActual + " de " + totalPaginas);

        // Mostrar las categorías en la tabla
        listarCategoriaProducto(listaCategoriaProductos);
        actualizarEstadoBotones();// Actualizar el estado de los botones
    }

    private void actualizarEstadoBotones() {
        btnAnterior.setEnabled(paginaActual > 1);
        btnSiguiente.setEnabled(paginaActual < totalPaginas);
    }

    public void eliminarCategoriaSeleccionada(int filaSeleccionada) {
        if (filaSeleccionada != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblCategoriaProducto.getValueAt(filaSeleccionada, 0).toString()); // Supone que la ID está en la primera columna
            if (Utils.mensajeConfirmacion(LiteralesTexto.ESTA_SEGURO_ELIMINAR_REGISTRO) == JOptionPane.YES_OPTION) {
                CategoriaProducto categoriaAEliminar = categoriaProductoFacade.findCategoriaProductoById(idSeleccionada);
                if(categoriaAEliminar != null){
                    try {
                        // Llamar al método para eliminar
                        categoriaProductoFacade.eliminarCategoria(categoriaAEliminar);
                        JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_ELIMINADO_CORRECTAMENTE);

                        // Actualizar la tabla después de eliminar
                        totalPaginas = categoriaProductoFacade.obtenerTotalPaginas(tamanioPagina);

                        // Verificar si la página actual es mayor que el total de páginas después de la eliminación
                        if (paginaActual > totalPaginas) {
                            paginaActual = totalPaginas; // Ajustar la página actual a la última disponible
                        }

                        // Actualizar la tabla después de eliminar
                        listarCategorias(paginaActual, tamanioPagina); // Volver a listar las categorías después de la eliminación

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, LiteralesTexto.ERROR_AL_ELIMINAR_EL_REGISTRO+ " : " + e.getMessage(), LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_NO_ENCONTRADO_EN_LA_BBDD, LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                }                
                
            }
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, LiteralesTexto.POR_FAVOR_SELECCIONE_UNA_REGISTRO_PARA_ELIMINAR);
        }
    }

    public void mostrarInformacionCategoria(int filaSeleccionada) {

        txtIdCategoria.setText(tblCategoriaProducto.getValueAt(filaSeleccionada, 0).toString());

        getDatosCategorias(filaSeleccionada);

        accionBotones(true, false, true);
    }

    private boolean validarDatosCategoria(){
        if(!validarCampo(txtNombre.getText(), LiteralesTexto.ERROR_NOMBRE_CAMPO_VACIO)){
            return false;
        }

        if (!validarCampo(txtDescripcion.getText(), LiteralesTexto.ERROR_VALOR_EDAD_VACIA)) {
            return false;
        }

        return true;
    }

    private boolean validarCampo(String valor, String mensajeError) {
        if (!Utils.validarCadena(valor)) {
            Utils.mensajeError(mensajeError);
            return false;
        }
        return true;
    }

    private void getDatosCategorias(int filaSeleccionada){
        // Cambiar al segundo panel donde están los JTextField
        tphCategoriaProducto.setSelectedIndex(1);

        txtNombre.setText(tblCategoriaProducto.getValueAt(filaSeleccionada, 1).toString());
        txtDescripcion.setText(tblCategoriaProducto.getValueAt(filaSeleccionada, 2).toString());
        
    }

    private CategoriaProducto getDatosCategoriaProducto(CategoriaProducto categoriaProducto) {

        categoriaProducto.setNombreCategoria(txtNombre.getText());
        categoriaProducto.setDescripcion(txtDescripcion.getText());
        categoriaProducto.setEstado((Estado) jcbEstado.getSelectedItem());
        return categoriaProducto;

    }
}
