/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifHorario.java
 *
 * Created on 02/09/2024, 09:57:06 PM
 */

package academiafulbito.vista.interfaces;

import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import javax.swing.JDesktopPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
/**
 *
 * @author Ronald J
 */
public class jifHorario extends javax.swing.JInternalFrame {

    /** Creates new form jifHorario */
    JDesktopPane jDesktopPane;

    int indicador;//para saber si estamos en modo de edicion
    private int idSeleccionada; // Variable para almacenar la ID de la categoría seleccionada
    private int paginaActual = 1;
    private int tamanioPagina = 5;//para el paginado de tabla
    private int totalPaginas;
    jifProfesores menuProfesores;
    jifCanchas menuCanchas;
    public jifHorario(JDesktopPane jdpModAF) {
        initComponents();
        jDesktopPane = jdpModAF;
        Utils.cargarComboDiasDeLaSemana(jcbDiasDeLaSemana);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tphHorarios = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspCategorias = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        btnNuevoHorario = new org.edisoncor.gui.button.ButtonRound();
        lblPaginaActual = new javax.swing.JLabel();
        btnAnterior = new org.edisoncor.gui.button.ButtonRound();
        btnSiguiente = new org.edisoncor.gui.button.ButtonRound();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbDiasDeLaSemana = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jPanel3 = new javax.swing.JPanel();
        jsHoraFin = new javax.swing.JSpinner(new SpinnerDateModel());
        jsHoraInicio = new javax.swing.JSpinner(new SpinnerDateModel());
        txtNombreProfesor = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdProfesor = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnBucarProfesor = new javax.swing.JButton();
        btnBuscarCategoria = new javax.swing.JButton();
        txtNombreCategoria = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdCategoria = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdCancha = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnBuscarCancha = new javax.swing.JButton();
        txtNombreCancha = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new org.edisoncor.gui.button.ButtonRound();

        setBackground(new java.awt.Color(204, 204, 255));
        setTitle("MANTENIMIENTO HORARIOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphHorarios.setFont(new java.awt.Font("Bookman Old Style", 1, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspCategorias.setBackground(new java.awt.Color(255, 255, 255));
        jspCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspCategorias.setOpaque(false);

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblHorarios.setOpaque(false);
        jspCategorias.setViewportView(tblHorarios);

        jPanel1.add(jspCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 250));

        btnNuevoHorario.setBackground(new java.awt.Color(156, 156, 247));
        btnNuevoHorario.setText("+ HORARIO");
        btnNuevoHorario.setFont(new java.awt.Font("Arial", 1, 18));
        btnNuevoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 50));

        lblPaginaActual.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        lblPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaginaActual.setText("10");
        jPanel1.add(lblPaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 220, 50));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior.setText("<<");
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 24));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, 50));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText(">>");
        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 24));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, -1, 50));

        tphHorarios.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLabel1.setForeground(new java.awt.Color(103, 98, 98));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO HORARIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 360, 20));

        jcbDiasDeLaSemana.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jPanel2.add(jcbDiasDeLaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 550, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELIGE TU HORARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JSpinner.DateEditor timeEditorHF = new JSpinner.DateEditor(jsHoraFin, "HH:mm");
        jsHoraFin.setEditor(timeEditorHF);
        jsHoraFin.setValue(new java.util.Date()); // valor inicial
        jsHoraFin.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jPanel3.add(jsHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 160, 40));

        JSpinner.DateEditor timeEditorHI = new JSpinner.DateEditor(jsHoraInicio, "HH:mm");
        jsHoraInicio.setEditor(timeEditorHI);
        jsHoraInicio.setValue(new java.util.Date()); // valor inicial
        jsHoraInicio.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jPanel3.add(jsHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 570, 90));

        txtNombreProfesor.setEditable(false);
        txtNombreProfesor.setDescripcion("Nombre Profesor*");
        txtNombreProfesor.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtNombreProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProfesorKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 450, 50));

        txtIdProfesor.setEditable(false);
        txtIdProfesor.setDescripcion("Id*");
        txtIdProfesor.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtIdProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProfesorKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, 50));

        btnBucarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/lupa.png"))); // NOI18N
        btnBucarProfesor.setBorderPainted(false);
        btnBucarProfesor.setContentAreaFilled(false);
        btnBucarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBucarProfesorActionPerformed(evt);
            }
        });
        jPanel2.add(btnBucarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 80, 60));

        btnBuscarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/lupa.png"))); // NOI18N
        btnBuscarCategoria.setBorderPainted(false);
        btnBuscarCategoria.setContentAreaFilled(false);
        btnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 80, 60));

        txtNombreCategoria.setEditable(false);
        txtNombreCategoria.setDescripcion("Nombre Categoria*");
        txtNombreCategoria.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtNombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCategoriaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 450, 50));

        txtIdCategoria.setEditable(false);
        txtIdCategoria.setDescripcion("Id*");
        txtIdCategoria.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtIdCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdCategoriaKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, 50));

        txtIdCancha.setEditable(false);
        txtIdCancha.setDescripcion("Id*");
        txtIdCancha.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtIdCancha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdCanchaKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 50));

        btnBuscarCancha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/lupa.png"))); // NOI18N
        btnBuscarCancha.setBorderPainted(false);
        btnBuscarCancha.setContentAreaFilled(false);
        btnBuscarCancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCanchaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 80, 60));

        txtNombreCancha.setEditable(false);
        txtNombreCancha.setDescripcion("Nombre Cancha*");
        txtNombreCancha.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtNombreCancha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCanchaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombreCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 450, 50));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 220, 70));

        btnGuardar.setBackground(new java.awt.Color(156, 156, 247));
        btnGuardar.setBorder(null);
        btnGuardar.setText("AÑADIR");
        btnGuardar.setBorderPainted(true);
        btnGuardar.setContentAreaFilled(true);
        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 170, 70));

        tphHorarios.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnNuevoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHorarioActionPerformed
        // TODO add your handling code here:
        indicador = 0;//para poder guardar
        tphHorarios.setSelectedIndex(1);
        limpiarCampos();
        habilitarCampos(true);
        accionBotones(true, true);
}//GEN-LAST:event_btnNuevoHorarioActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            //listarCategorias(Utils.cargarPaginado(paginaActual, tamanioPagina, lblPaginaActual, jfPrincipal.menuCategorias));
            //listarCategorias(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
            //listarCategorias(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtNombreProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProfesorKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(c)); // Convertir a mayúsculas
}//GEN-LAST:event_txtNombreProfesorKeyTyped

    private void txtIdProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProfesorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProfesorKeyTyped

    private void txtNombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCategoriaKeyTyped

    private void txtIdCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCategoriaKeyTyped

    private void txtIdCanchaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCanchaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCanchaKeyTyped

    private void txtNombreCanchaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCanchaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCanchaKeyTyped

    private void btnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCategoriaActionPerformed
        // TODO add your handling code here:
        // Si el internalFrame de categorías no existe o está cerrado, lo instanciamos
        if (jfPrincipal.menuCategorias == null || jfPrincipal.menuCategorias.isClosed()) {
            jfPrincipal.menuCategorias = new jifCategorias(jDesktopPane); // Instanciamos la ventana de Categorías
            // Llamamos al método para gestionar la visualización
            Utils.visualizarInternalFrame(jfPrincipal.menuCategorias, jDesktopPane);
        }
        jfPrincipal.menuCategorias.toFront(); // Traer al frente
    }//GEN-LAST:event_btnBuscarCategoriaActionPerformed

    private void btnBucarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBucarProfesorActionPerformed
        // TODO add your handling code here:
        if(jfPrincipal.menuProfesores == null || jfPrincipal.menuProfesores.isClosed()){
            jfPrincipal.menuProfesores = new jifProfesores(jDesktopPane);
            Utils.visualizarInternalFrame(jfPrincipal.menuProfesores, jDesktopPane);
        }
        jfPrincipal.menuProfesores.permiteSelFila=0;//este valor permite seleccionar con un clic en la fila de la tabla de profesores
        jfPrincipal.menuProfesores.toFront();
    }//GEN-LAST:event_btnBucarProfesorActionPerformed

    private void btnBuscarCanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCanchaActionPerformed
        // TODO add your handling code here:
        if(jfPrincipal.menuCanchas == null || jfPrincipal.menuCanchas.isClosed()){
            jfPrincipal.menuCanchas = new jifCanchas(jDesktopPane);
            Utils.visualizarInternalFrame(jfPrincipal.menuCanchas, jDesktopPane);
        }
        jfPrincipal.menuCanchas.toFront();
    }//GEN-LAST:event_btnBuscarCanchaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        habilitarCampos(false);
        tphHorarios.setSelectedIndex(0);
        accionBotones(false, false);
}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        /*try {
            if (validarDatosCategoria()) {
                String cadenaMensaje = 0 == indicador ? LiteralesTexto.ESTA_SEGURO_GUARDAR_NUEVO_REGISTRO : LiteralesTexto.ESTA_SEGURO_MODIFICAR_REGISTRO;
                if (Utils.mensajeConfirmacion(cadenaMensaje) == JOptionPane.YES_OPTION) {
                    Categoria categoria;
                    switch (indicador) {
                        case 0://registrar categoria
                            categoria = new Categoria();
                            categoriaFacade.guardarCategoria(getDatosCategoria(categoria));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                            break;
                        case 1://actualizar categoria
                            categoria = categoriaFacade.findCategoriaById(idSeleccionada);
                            categoriaFacade.actualizarCategoria(getDatosCategoria(categoria));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_ACTUALIZADO_CORRECTAMENTE);
                            break;
                    }

                    listarCategorias(paginaActual, tamanioPagina);
                    limpiarCampos();
                    habilitarCampos(false);
                    accionBotones(false, false);
                    btnGuardar.setText("Añadir");
                    indicador = 0;
                    tphCategorias.setSelectedIndex(0);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }*/
}//GEN-LAST:event_btnGuardarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnAnterior;
    private javax.swing.JButton btnBucarProfesor;
    private javax.swing.JButton btnBuscarCancha;
    private javax.swing.JButton btnBuscarCategoria;
    private javax.swing.JButton btnCancelar;
    private org.edisoncor.gui.button.ButtonRound btnGuardar;
    private org.edisoncor.gui.button.ButtonRound btnNuevoHorario;
    private org.edisoncor.gui.button.ButtonRound btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.edisoncor.gui.comboBox.ComboBoxRound jcbDiasDeLaSemana;
    private javax.swing.JSpinner jsHoraFin;
    private javax.swing.JSpinner jsHoraInicio;
    private javax.swing.JScrollPane jspCategorias;
    private javax.swing.JLabel lblPaginaActual;
    private javax.swing.JTable tblHorarios;
    private javax.swing.JTabbedPane tphHorarios;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdCancha;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdCategoria;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdProfesor;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtNombreCancha;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtNombreCategoria;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtNombreProfesor;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos(){
        jcbDiasDeLaSemana.setSelectedIndex(0);
        jsHoraInicio.setValue(new java.sql.Time(System.currentTimeMillis()));
        jsHoraFin.setValue(new java.sql.Time(System.currentTimeMillis()));
        txtIdProfesor.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombreProfesor.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtIdCategoria.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombreCategoria.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtIdCancha.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombreCancha.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void habilitarCampos(boolean band){
        if(indicador == 0){
            jcbDiasDeLaSemana.setSelectedIndex(0);
            jcbDiasDeLaSemana.setEnabled(band);
        } else{
            jcbDiasDeLaSemana.setEnabled(band);
        }
        jsHoraInicio.setEnabled(band);
        jsHoraFin.setEnabled(band);
        txtIdProfesor.setEditable(band);
        txtNombreProfesor.setEditable(band);
        txtIdCategoria.setEditable(band);
        txtNombreCategoria.setEditable(band);
        txtIdCancha.setEditable(band);
        txtNombreCancha.setEditable(band);
    }

    private void accionBotones(boolean d, boolean e) {
        btnCancelar.setEnabled(d);
        btnGuardar.setEnabled(e);
    }
}