/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCategorias.java
 *
 * Created on 02/08/2024, 02:42:40 PM
 */

package academiafulbito.vista.interfaces;

import academiafulbito.controlador.beans.LugarEntrenamientoFacade;
import academiafulbito.modelo.entidades.LugarEntrenamiento;
import academiafulbito.modelo.enums.Estado;
import academiafulbito.vista.reportes.Reportes;
import academiafulbito.vista.utilidades.DialogUtils;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import java.awt.Cursor;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Checa
 */
public class jifLugarEntrenamiento extends javax.swing.JInternalFrame {

    JDesktopPane jdp;
    public static LugarEntrenamientoFacade lugarEntrenamientoFacade;
    DefaultTableModel modelo;
    String[] nombreColumnas = {
        LiteralesTexto.LITERAL_ID,
        LiteralesTexto.LITERAL_NOMBRE,
        LiteralesTexto.LITERAL_DIRECCION,
        LiteralesTexto.LITERAL_UBIGEO,
        LiteralesTexto.LITERAL_ESTADO,
        LiteralesTexto.LITERAL_VER,
        LiteralesTexto.LITERAL_EDITAR,
        LiteralesTexto.LITERAL_ELIMINAR
    };
    int indicador;//para saber si estamos en modo de edicion
    private int idSeleccionada; // Variable para almacenar la ID del lugarEntrenamiento seleccionada
    private int paginaActual = 1;
    private int tamanioPagina = 5;//para el paginado de tabla
    private int totalPaginas;
    public static int permiteSelFila = -1;//este valor no permite seleccionar la fila en la tabla
    /** Creates new form jifCategorias */
    public jifLugarEntrenamiento(JDesktopPane jdpModAF){
        initComponents();
        jdp=jdpModAF;
        Utils.cargarComboEstado(jcbEstado);
        accionBotones(false, false, false);
        lugarEntrenamientoFacade = new LugarEntrenamientoFacade();
        listarLugarEntrenamientos(paginaActual, tamanioPagina);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tphLugarEntrenamientos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspLugarEntrenamientos = new javax.swing.JScrollPane();
        tblLugarEntrenamientos = new javax.swing.JTable();
        lblPaginaActual = new javax.swing.JLabel();
        btnAnterior = new org.edisoncor.gui.button.ButtonRound();
        btnSiguiente = new org.edisoncor.gui.button.ButtonRound();
        btnNuevaLugarEntrenamiento = new javax.swing.JButton();
        btnRepCanchasPorLugaEnt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtDireccion = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtUbigeo = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jcbEstado = new org.edisoncor.gui.comboBox.ComboBoxRound();
        txtIdLugarEntrenamiento = new javax.swing.JTextField();
        btnImprimirLugarEntrenamiento = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();


        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setTitle("MANTENIMIENTO LUGAR ENTRENAMIENTO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphLugarEntrenamientos.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspLugarEntrenamientos.setBackground(new java.awt.Color(255, 255, 255));
        jspLugarEntrenamientos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspLugarEntrenamientos.setOpaque(false);

        tblLugarEntrenamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLugarEntrenamientos.setOpaque(false);
        tblLugarEntrenamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLugarEntrenamientosMouseClicked(evt);
            }
        });
        tblLugarEntrenamientos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblLugarEntrenamientosMouseMoved(evt);
            }
        });
        jspLugarEntrenamientos.setViewportView(tblLugarEntrenamientos);

        jPanel1.add(jspLugarEntrenamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1150, 290));

        lblPaginaActual.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        lblPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaginaActual.setText("10");
        jPanel1.add(lblPaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 220, 50));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior.setText("<<");
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 24));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, -1, 50));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText(">>");
        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 24));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, -1, 50));

        btnNuevaLugarEntrenamiento.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        btnNuevaLugarEntrenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/nuevo.png"))); // NOI18N
        btnNuevaLugarEntrenamiento.setText("<html><center>NUEVO<br>LUGAR ENT.</center></html>");
        btnNuevaLugarEntrenamiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNuevaLugarEntrenamiento.setContentAreaFilled(false);
        btnNuevaLugarEntrenamiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaLugarEntrenamiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevaLugarEntrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaLugarEntrenamientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaLugarEntrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 170, 120));

        btnRepCanchasPorLugaEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/imprimir-pdf.png"))); // NOI18N
        btnRepCanchasPorLugaEnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRepCanchasPorLugaEnt.setContentAreaFilled(false);
        btnRepCanchasPorLugaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepCanchasPorLugaEntActionPerformed(evt);
            }
        });
        jPanel1.add(btnRepCanchasPorLugaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 120, 70));

        tphLugarEntrenamientos.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setEditable(false);
        txtNombre.setDescripcion("Nombre*");
        txtNombre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 720, 40));

        txtDireccion.setEditable(false);
        txtDireccion.setDescripcion("Dirección*");
        txtDireccion.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 720, 40));

        txtUbigeo.setEditable(false);
        txtUbigeo.setDescripcion("Ubigeo*");
        txtUbigeo.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtUbigeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 720, 40));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLabel1.setForeground(new java.awt.Color(103, 98, 98));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO LUGAR DE ENTRENAMIENTO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 520, 20));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 190, 80));

        jcbEstado.setEnabled(false);
        jcbEstado.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 220, 40));
        jPanel2.add(txtIdLugarEntrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));
        txtIdLugarEntrenamiento.setVisible(false);

        btnImprimirLugarEntrenamiento.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnImprimirLugarEntrenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/reportes.png"))); // NOI18N
        btnImprimirLugarEntrenamiento.setText("REPORTE");
        btnImprimirLugarEntrenamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimirLugarEntrenamiento.setContentAreaFilled(false);
        btnImprimirLugarEntrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirLugarEntrenamientoActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimirLugarEntrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 190, -1));

        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/guardar-datos.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 190, 90));


        tphLugarEntrenamientos.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphLugarEntrenamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        habilitarCampos(false);
        tphLugarEntrenamientos.setSelectedIndex(0);
        accionBotones(false, false, false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        int totalDePaginas = lugarEntrenamientoFacade.obtenerTotalPaginas(tamanioPagina);
        if (paginaActual < totalDePaginas) {
            paginaActual++;
            listarLugarEntrenamientos(paginaActual, tamanioPagina);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            listarLugarEntrenamientos(paginaActual, tamanioPagina);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void tblLugarEntrenamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLugarEntrenamientosMouseClicked
        // TODO add your handling code here:
        switch(permiteSelFila){
            case 0://permite llamarlo desde una ventana externa
                int nroFila = tblLugarEntrenamientos.getSelectedRow();
                if(nroFila != -1){
                    jfPrincipal.menuCanchas.txtIdLugarE.setText(tblLugarEntrenamientos.getValueAt(nroFila, 0).toString());    // Encuentra el ID o PK ...
                    jfPrincipal.menuCanchas.txtNombreLugarE.setText(tblLugarEntrenamientos.getValueAt(nroFila, 1).toString()+" "+tblLugarEntrenamientos.getValueAt(nroFila, 2).toString());

                }
                try{
                    setClosed(true);
                }catch(Exception ex){
                    ex.printStackTrace();
                }
                break;
        }
    }//GEN-LAST:event_tblLugarEntrenamientosMouseClicked

    

    private void btnNuevaLugarEntrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaLugarEntrenamientoActionPerformed
        // TODO add your handling code here:
        indicador = 0;//para poder guardar
        tphLugarEntrenamientos.setSelectedIndex(1);
        limpiarCampos();
        habilitarCampos(true);
        accionBotones(true, true, false);
    }//GEN-LAST:event_btnNuevaLugarEntrenamientoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String cadenaMensaje = 0 == indicador ? LiteralesTexto.ESTA_SEGURO_GUARDAR_NUEVO_REGISTRO : LiteralesTexto.ESTA_SEGURO_MODIFICAR_REGISTRO;
        if (Utils.mensajeConfirmacion(cadenaMensaje) == JOptionPane.YES_OPTION) {
            LugarEntrenamiento lugarEntrenamiento;
            switch(indicador){
                case 0://registrar lugarEntrenamiento
                    lugarEntrenamiento = new LugarEntrenamiento();
                    lugarEntrenamientoFacade.guardarLugarEntrenamiento(getDatosLugarEntrenamiento(lugarEntrenamiento));
                    Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                    break;
                case 1://actualizar lugarEntrenamiento
                    lugarEntrenamiento = lugarEntrenamientoFacade.findLugarEntrenamientoById(idSeleccionada);
                    lugarEntrenamientoFacade.actualizarLugarEntrenamiento(getDatosLugarEntrenamiento(lugarEntrenamiento));
                    Utils.mensajeInformacion(LiteralesTexto.REGISTRO_ACTUALIZADO_CORRECTAMENTE);
                    break;
            }

            listarLugarEntrenamientos(lugarEntrenamientoFacade.getListadoLugarEntrenamientos());
            limpiarCampos();
            habilitarCampos(false);
            accionBotones(false, false, false);
            btnGuardar.setText("Añadir");
            indicador = 0;
            tphLugarEntrenamientos.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblLugarEntrenamientosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLugarEntrenamientosMouseMoved
        // TODO add your handling code here:
        int col = tblLugarEntrenamientos.columnAtPoint(evt.getPoint());
        int row = tblLugarEntrenamientos.rowAtPoint(evt.getPoint());
        if (col >= 0 && (tblLugarEntrenamientos.getColumnName(col).equals(LiteralesTexto.LITERAL_VER) ||
                         tblLugarEntrenamientos.getColumnName(col).equals(LiteralesTexto.LITERAL_EDITAR) ||
                         tblLugarEntrenamientos.getColumnName(col).equals(LiteralesTexto.LITERAL_ELIMINAR))) {
            tblLugarEntrenamientos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            tblLugarEntrenamientos.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_tblLugarEntrenamientosMouseMoved

    private void btnImprimirLugarEntrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirLugarEntrenamientoActionPerformed
        // TODO add your handling code here:
        Map parametros = new HashMap();
        parametros.put("ID_lugar", txtIdLugarEntrenamiento.getText()); // Ejemplo de parámetro para el reporte
        // Llamar al método para generar y mostrar el reporte
        Reportes.imprimirReporte(parametros, "rp_lugar_entrenamientos.jasper");
    }//GEN-LAST:event_btnImprimirLugarEntrenamientoActionPerformed

    private void btnRepCanchasPorLugaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepCanchasPorLugaEntActionPerformed
        // TODO add your handling code here:
        // Definir los parámetros necesarios para el reporte
        Map parametros = new HashMap();
        // Llamar al método para generar y mostrar el reporte
        Reportes.imprimirReporte(parametros, "rp_canchas_por_lugar_entrenam.jasper");
}//GEN-LAST:event_btnRepCanchasPorLugaEntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimirLugarEntrenamiento;
    private javax.swing.JButton btnNuevaLugarEntrenamiento;
    private javax.swing.JButton btnRepCanchasPorLugaEnt;
    private org.edisoncor.gui.button.ButtonRound btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.comboBox.ComboBoxRound jcbEstado;
    private javax.swing.JScrollPane jspLugarEntrenamientos;
    private javax.swing.JLabel lblPaginaActual;
    private javax.swing.JTable tblLugarEntrenamientos;
    private javax.swing.JTabbedPane tphLugarEntrenamientos;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtDireccion;
    private javax.swing.JTextField txtIdLugarEntrenamiento;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtNombre;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtUbigeo;
    // End of variables declaration//GEN-END:variables

    private void listarLugarEntrenamientos(int paginaActual, int tamanioPagina) {
        totalPaginas = lugarEntrenamientoFacade.obtenerTotalPaginas(tamanioPagina);

        List<LugarEntrenamiento> listaLugarEntrenamiento = lugarEntrenamientoFacade.listarEntidadesPaginadas(paginaActual, tamanioPagina);

        // Actualizar el JLabel con la página actual
        lblPaginaActual.setText("Página " + paginaActual + " de " + totalPaginas);

        // Mostrar las categorías en la tabla
        listarLugarEntrenamientos(listaLugarEntrenamiento);
        actualizarEstadoBotones();// Actualizar el estado de los botones
    }

    private void listarLugarEntrenamientos(List<LugarEntrenamiento> listaLugarEntrenamientos){
        // Selecciona el primer tab en un JTabbedPane
        tphLugarEntrenamientos.setSelectedIndex(0);
        
        modelo = Utils.generarModeloTabla(nombreColumnas);

        // Asignar el modelo a la tabla
        tblLugarEntrenamientos.setModel(modelo);

        int[] anchoColumnas = {15, 55, 75, 25, 10, 12, 21, 25}; // Anchos específicos para cada columna
        Utils.setAnchoColumnas(tblLugarEntrenamientos, anchoColumnas);
        Utils.ocultarColumnas(tblLugarEntrenamientos, 0);//ocultar la primera columna
        Utils.ocultarColumnas(tblLugarEntrenamientos, 4);//ocultar columna estado
        
        // limpia los datos existentes en la tabla.
        Utils.limpiarModeloTabla(modelo, tblLugarEntrenamientos);

        // Verificar si la lista tiene elementos
        if (listaLugarEntrenamientos.size() > 0) {
            // Iterar sobre la lista y agregar cada objeto a la tabla
            for (LugarEntrenamiento lugarEntrenamiento : listaLugarEntrenamientos) {

                // Crea un array de objetos con los datos del objeto para agregar a la tabla.
                Object[] fila = new Object[]{
                    lugarEntrenamiento.getIdLugar(),
                    lugarEntrenamiento.getNombre(),
                    lugarEntrenamiento.getDireccion(),
                    lugarEntrenamiento.getUbigeo(),
                    lugarEntrenamiento.getEstado(),
                    LiteralesTexto.LITERAL_VER,
                    LiteralesTexto.LITERAL_EDITAR,
                    LiteralesTexto.LITERAL_ELIMINAR
                };
                modelo.addRow(fila); // Agregar la fila al modelo de la tabla
            }
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblLugarEntrenamientos.setDefaultRenderer(Object.class, new Utils(14));
            
            Utils.configurarEstiloTabla(tblLugarEntrenamientos, jspLugarEntrenamientos);
            Utils.configurarBotonesAccion(tblLugarEntrenamientos);
        }
    }

    private LugarEntrenamiento getDatosLugarEntrenamiento(LugarEntrenamiento lugarEntrenamiento){
        lugarEntrenamiento.setNombre(txtNombre.getText());
        lugarEntrenamiento.setDireccion(txtDireccion.getText());
        lugarEntrenamiento.setUbigeo(txtUbigeo.getText());
        lugarEntrenamiento.setEstado((Estado)jcbEstado.getSelectedItem());

        return lugarEntrenamiento;
    }

    private void limpiarCampos() {
        txtNombre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtDireccion.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtUbigeo.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void habilitarCampos(boolean band){
        txtNombre.setEditable(band);
        txtDireccion.setEditable(band);
        txtUbigeo.setEditable(band);
        if(indicador == 0){
            jcbEstado.setSelectedIndex(0);
            jcbEstado.setEnabled(!band);
        } else{
            jcbEstado.setEnabled(band);
        }
        
    }

    private void accionBotones(boolean d, boolean e, boolean f) {
        btnCancelar.setEnabled(d);
        btnGuardar.setEnabled(e);
        btnImprimirLugarEntrenamiento.setEnabled(f);
    }

    public void cargarDatosEnFormulario(int row) {
        if (row != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblLugarEntrenamientos.getValueAt(row, 0).toString()); // Supone que la ID está en la primera columna

            // Obtener los datos de la fila seleccionada
            String nombre = (String) tblLugarEntrenamientos.getValueAt(row, 1);
            String direccion = (String)tblLugarEntrenamientos.getValueAt(row, 2);
            String ubigeo = (String)tblLugarEntrenamientos.getValueAt(row, 3);
            Estado estado = (Estado)tblLugarEntrenamientos.getValueAt(row, 4);

            // Asignar los datos a los JTextField en el segundo panel
            txtNombre.setText(nombre);
            txtDireccion.setText(direccion);
            txtUbigeo.setText(ubigeo);

            // Seleccionar el estado en el JComboBox
            jcbEstado.setSelectedItem(estado);

            // Cambiar al segundo panel donde están los JTextField
            tphLugarEntrenamientos.setSelectedIndex(1);
            btnGuardar.setText("Modificar");
            indicador = 1;
            accionBotones(true, true, false);
            habilitarCampos(true);
        } else{
            //colocar alguna alerta
        }
    }

    private void actualizarEstadoBotones() {
        btnAnterior.setEnabled(paginaActual > 1);
        btnSiguiente.setEnabled(paginaActual < totalPaginas);
    }

    public void eliminarLugarEntrenamSeleccionado(int filaSeleccionada) {
        if (filaSeleccionada != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblLugarEntrenamientos.getValueAt(filaSeleccionada, 0).toString()); // Supone que la ID está en la primera columna
            if (Utils.mensajeConfirmacion(LiteralesTexto.ESTA_SEGURO_ELIMINAR_REGISTRO) == JOptionPane.YES_OPTION) {
                LugarEntrenamiento lugarEAEliminar = lugarEntrenamientoFacade.findLugarEntrenamientoById(idSeleccionada);
                if(lugarEAEliminar != null){
                    try {
                        // Llamar al método para eliminar
                        lugarEntrenamientoFacade.eliminarLugarEntrenamiento(lugarEAEliminar);
                        JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_ELIMINADO_CORRECTAMENTE);

                        // Actualizar la tabla después de eliminar
                        totalPaginas = lugarEntrenamientoFacade.obtenerTotalPaginas(tamanioPagina);

                        // Verificar si la página actual es mayor que el total de páginas después de la eliminación
                        if (paginaActual > totalPaginas) {
                            paginaActual = totalPaginas; // Ajustar la página actual a la última disponible
                        }

                        // Actualizar la tabla después de eliminar
                        listarLugarEntrenamientos(paginaActual, tamanioPagina); // Volver a listar las categorías después de la eliminación

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, LiteralesTexto.ERROR_AL_ELIMINAR_EL_REGISTRO+ " : " + e.getMessage(), LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_NO_ENCONTRADO_EN_LA_BBDD, LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                }

            }
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, LiteralesTexto.POR_FAVOR_SELECCIONE_UNA_REGISTRO_PARA_ELIMINAR);
        }
    }



    public void mostrarInformacionLugarE(int filaSeleccionada) {
        tphLugarEntrenamientos.setSelectedIndex(1);
        txtIdLugarEntrenamiento.setText(tblLugarEntrenamientos.getValueAt(filaSeleccionada, 0).toString());
        //datos del alumno
        txtNombre.setText(tblLugarEntrenamientos.getValueAt(filaSeleccionada, 1).toString());
        txtDireccion.setText(tblLugarEntrenamientos.getValueAt(filaSeleccionada, 2).toString());
        txtUbigeo.setText(tblLugarEntrenamientos.getValueAt(filaSeleccionada, 3).toString());

        accionBotones(true, false, true);

    }
}
