/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifPagos.java
 *
 * Created on 11/12/2024, 08:27:55 PM
 */

package academiafulbito.vista.interfaces;

import academiafulbito.modelo.entidades.ProductoServicio;
import academiafulbito.controlador.beans.AlumnoFacade;
import academiafulbito.controlador.beans.PadreFacade;
import academiafulbito.modelo.entidades.Alumno;
import academiafulbito.modelo.entidades.Padre;
import academiafulbito.vista.utilidades.Imagen;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import java.awt.Image;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronald J
 */
public class jifPagos extends javax.swing.JInternalFrame {

    /** Creates new form jifPagos */
    
    public static ProductoServicio productoServicio;
    JDesktopPane jdp;
    private PadreFacade padreFacade;
    private AlumnoFacade alumnoFacade;
    jifProductoServicios menuProductoServicios;
    private BigDecimal totalAPagar = BigDecimal.ZERO;
    private int paginaActual = 1;
    private int tamanioPagina = 10;
    public char tipo='1';
    
    public jifPagos(JDesktopPane jdpModAF) {
        initComponents();
        jdp = jdpModAF;
        padreFacade = new PadreFacade();
        alumnoFacade = new AlumnoFacade();
        jpMatricula.setVisible(false);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcionesPago = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jcbTipoConsulta = new javax.swing.JComboBox();
        txtDatoBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblFotoAlumno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtApellidosAlumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombresAlumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombresApellidosPadre = new javax.swing.JTextField();
        txtDniPadre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarConcepto = new javax.swing.JButton();
        txtConceptoPago = new javax.swing.JTextField();
        btnAgregarConcepto = new javax.swing.JButton();
        btnQuitarConcepto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jdchFechaPago = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbTipoCpbte = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtCorrelativo = new javax.swing.JTextField();
        txtPagoEfectivo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPagoYape = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPagoPlin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotalPago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jspTblItemsConceptos = new javax.swing.JScrollPane();
        tblItemsConceptos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtCodConceptoPago = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnVerPagos = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        jpMatricula = new javax.swing.JPanel();
        txtIdMatricula = new javax.swing.JTextField();
        btnBuscarMatricula = new javax.swing.JButton();
        txtDetallesMatricula = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rbPagarMatricula = new javax.swing.JRadioButton();
        rbPagarOtrosServicios = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtDniAlumno = new javax.swing.JTextField();

        setClosable(true);
        setTitle("PAGOS DIVERSOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Consultar Datos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbTipoConsulta.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jcbTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI ALUMNO" }));
        jcbTipoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoConsultaActionPerformed(evt);
            }
        });
        jPanel4.add(jcbTipoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, 150, 50));

        txtDatoBusqueda.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtDatoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatoBusquedaKeyTyped(evt);
            }
        });
        jPanel4.add(txtDatoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 210, 50));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 90, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 510, 90));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Foto Alumno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 0, 12))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(lblFotoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 160));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 190, 190));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel1.setText("APELLIDOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        txtApellidosAlumno.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        getContentPane().add(txtApellidosAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 820, 30));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel2.setText("NOMBRES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        txtNombresAlumno.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        getContentPane().add(txtNombresAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 570, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel3.setText("APODERADO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        txtNombresApellidosPadre.setBackground(new java.awt.Color(255, 255, 153));
        txtNombresApellidosPadre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        getContentPane().add(txtNombresApellidosPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 570, 30));

        txtDniPadre.setBackground(new java.awt.Color(255, 255, 153));
        txtDniPadre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        getContentPane().add(txtDniPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 180, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("PRECIO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 180, 20));

        btnBuscarConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/buscar.png"))); // NOI18N
        btnBuscarConcepto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBuscarConcepto.setBorderPainted(false);
        btnBuscarConcepto.setContentAreaFilled(false);
        btnBuscarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConceptoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 50));

        txtConceptoPago.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtConceptoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 710, 50));

        btnAgregarConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/agregar.png"))); // NOI18N
        btnAgregarConcepto.setBorderPainted(false);
        btnAgregarConcepto.setContentAreaFilled(false);
        btnAgregarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConceptoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 60, 50));

        btnQuitarConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/quitar.png"))); // NOI18N
        btnQuitarConcepto.setBorderPainted(false);
        btnQuitarConcepto.setContentAreaFilled(false);
        btnQuitarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarConceptoActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitarConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 60, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jdchFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 30));

        jLabel6.setText("CORRELATIVO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, 20));

        jLabel8.setText("FECHA DEL PAGO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jcbTipoCpbte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcbTipoCpbte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 30));

        jLabel9.setText("TIPO CPBTE.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        txtCorrelativo.setBackground(new java.awt.Color(204, 255, 255));
        txtCorrelativo.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtCorrelativo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCorrelativo.setText("000-000");
        jPanel1.add(txtCorrelativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, 30));

        txtPagoEfectivo.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtPagoEfectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPagoEfectivo.setText("0.00");
        jPanel1.add(txtPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 30));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel12.setText("YAPE  ( S/.)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 30));

        txtPagoYape.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtPagoYape.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPagoYape.setText("0.00");
        jPanel1.add(txtPagoYape, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 30));

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel13.setText("PLIN ( S/.)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 30));

        txtPagoPlin.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtPagoPlin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPagoPlin.setText("0.00");
        jPanel1.add(txtPagoPlin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 30));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel14.setText("EFECTIVO  ( S/.)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 30));

        txtTotalPago.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        txtTotalPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPago.setText("0.00");
        jPanel1.add(txtTotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 150, 30));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel11.setText("TOTAL A PAGAR");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 310, 240));

        tblItemsConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID.PROD", "ID.CAT.PROD", "NOMBRE PRODUCTO", "PRECIO", "CANT", "TOTAL"
            }
        ));
        jspTblItemsConceptos.setViewportView(tblItemsConceptos);

        jPanel2.add(jspTblItemsConceptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 850, 240));

        jLabel7.setText("CODIGO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        txtCodConceptoPago.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtCodConceptoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 50));

        txtPrecio.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 180, 50));

        jLabel16.setText("CONCEPTO DE PAGO");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 310, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1190, 340));

        btnVerPagos.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnVerPagos.setText("VER PAGOS");
        btnVerPagos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVerPagos.setContentAreaFilled(false);
        btnVerPagos.setEnabled(false);
        btnVerPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPagosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 190, 70));

        jLabel10.setBackground(new java.awt.Color(255, 255, 153));
        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        jLabel10.setText("     DNI");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 70, 30));

        btnPagar.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        btnPagar.setForeground(new java.awt.Color(0, 0, 255));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/guardar-datos.png"))); // NOI18N
        btnPagar.setText("PAGAR");
        btnPagar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPagar.setContentAreaFilled(false);
        getContentPane().add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 250, 70));

        jpMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpMatricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdMatricula.setEditable(false);
        jpMatricula.add(txtIdMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        btnBuscarMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/buscar.png"))); // NOI18N
        btnBuscarMatricula.setBorderPainted(false);
        btnBuscarMatricula.setContentAreaFilled(false);
        btnBuscarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatriculaActionPerformed(evt);
            }
        });
        jpMatricula.add(btnBuscarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 60));

        txtDetallesMatricula.setEditable(false);
        jpMatricula.add(txtDetallesMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 850, 30));

        jLabel15.setText("ID MATRICULA");
        jpMatricula.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 20));

        jLabel17.setText("DETALLES DE LA MATRICULA DEL ALUMNO");
        jpMatricula.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 310, 20));

        getContentPane().add(jpMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 1020, 60));

        bgOpcionesPago.add(rbPagarMatricula);
        rbPagarMatricula.setFont(new java.awt.Font("Tahoma", 1, 14));
        rbPagarMatricula.setText("PAGAR MATRICULA");
        rbPagarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagarMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(rbPagarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, -1));

        bgOpcionesPago.add(rbPagarOtrosServicios);
        rbPagarOtrosServicios.setFont(new java.awt.Font("Tahoma", 1, 14));
        rbPagarOtrosServicios.setSelected(true);
        rbPagarOtrosServicios.setText("OTROS SERVICIOS");
        rbPagarOtrosServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagarOtrosServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(rbPagarOtrosServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("    DNI :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 70, 30));

        txtDniAlumno.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        getContentPane().add(txtDniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagosActionPerformed
        // TODO add your handling code here:
        
}//GEN-LAST:event_btnVerPagosActionPerformed

    private void btnAgregarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConceptoActionPerformed
        // TODO add your handling code here:
        //para la segunda condicion se busca el codConcepto dentro de la tabla de agregados, haber si ya existe tal codigo
        if (validarConceptoAgregado()/* && !Utils.validarDatoRegistroTabla(tblItemsConceptos, 1, txtCodConceptoPago.getText())*/) {
            DefaultTableModel tableModel = (DefaultTableModel) tblItemsConceptos.getModel();

            if (productoServicio != null) {
                Object item[] = {
                    "" + productoServicio.getIdProducto(),
                    "" + productoServicio.getCategoriaProducto().getIdCategoriaProd(),
                    productoServicio.getNombreProducto(),
                    productoServicio.getPrecio(),
                    "1",
                    productoServicio.getPrecio()
                };
                tableModel.addRow(item);

                //actualizar el total
                totalAPagar = totalAPagar.add(productoServicio.getPrecio());
                actualizarTotalAPagar();
                activarBotonProcesoPago();
            }
            int[] anchoColumnas = {
                15,// idProd
                15, //idCatPro
                120, //prod
                20, //precio
                20, //cantidad
                20 // total
            }; // Anchos específicos para cada columna
            Utils.setAnchoColumnas(tblItemsConceptos, anchoColumnas);
            Utils.ocultarColumnas(tblItemsConceptos, 0);
            Utils.ocultarColumnas(tblItemsConceptos, 1);
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblItemsConceptos.setDefaultRenderer(Object.class, new Utils(14));

            // Establece el modo de selección de filas para permitir solo una selección a la vez.
            tblItemsConceptos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            limpiarCamposProductosServ();
        } else {
            Utils.mensajeError("ERROR!!, PARA AGREGAR EL CONCEPTO DE PAGO.");
        }
    }//GEN-LAST:event_btnAgregarConceptoActionPerformed

    private void btnBuscarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConceptoActionPerformed
        // TODO add your handling code here:
        if (Utils.validarCadena(txtDniAlumno.getText())) {
            if (jfPrincipal.menuProductoServicios == null || jfPrincipal.menuProductoServicios.isClosed()) {
                jfPrincipal.menuProductoServicios = new jifProductoServicios(jdp);
                Utils.visualizarInternalFrame(jfPrincipal.menuProductoServicios, jdp);
            }
            jfPrincipal.menuProductoServicios.permiteSelFila = 0;
            //String texto = rbPagarOtrosServicios.getText();
            //int tipo = Integer.parseInt(texto);
            jfPrincipal.menuProductoServicios.tipo = tipo;
            jfPrincipal.menuProductoServicios.listarProductoServicio(paginaActual, tamanioPagina);
            jfPrincipal.menuProductoServicios.toFront();
        } else {
            Utils.mensajeError("ERROR!!, DEBES BUSCAR EL ALUMNO PRIMERO");
        }

    }//GEN-LAST:event_btnBuscarConceptoActionPerformed

    private void txtDatoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoBusquedaKeyTyped
        char c = evt.getKeyChar();
        // Permitir solo dígitos y hasta 2 caracteres
        if (!Character.isDigit(c) || txtDatoBusqueda.getText().length() >= 12) {
            evt.consume(); // Ignorar el evento de tecla
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoBusquedaKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrarDatosPersona(txtDatoBusqueda.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcbTipoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoConsultaActionPerformed
        limpiarCamposBusquedaPersona(); // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoConsultaActionPerformed

    private void btnQuitarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarConceptoActionPerformed
        // TODO add your handling code here:
        int nroFila=tblItemsConceptos.getSelectedRow();
        if(nroFila != -1){
            int retorno=Utils.mensajeConfirmacion(LiteralesTexto.ESTA_SEGURO_ELIMINAR_REGISTRO);
            switch(retorno){
                case JOptionPane.YES_OPTION:{
                    DefaultTableModel modelo=(DefaultTableModel)tblItemsConceptos.getModel();
                    BigDecimal filaPrecioEliminar = (BigDecimal)modelo.getValueAt(nroFila, 5);
                    modelo.removeRow(nroFila);

                    //actualizar el total
                    totalAPagar = totalAPagar.subtract(filaPrecioEliminar);
                    actualizarTotalAPagar();
                    activarBotonProcesoPago();
                }
                break;
                case JOptionPane.NO_OPTION:{}break;
            }
        } else if(nroFila == -1){
            Utils.mensajeError(LiteralesTexto.LITERAL_ELIMINAR_REGISTRO);
        }
    }//GEN-LAST:event_btnQuitarConceptoActionPerformed

    private void rbPagarOtrosServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagarOtrosServiciosActionPerformed
        // TODO add your handling code here:
        jpMatricula.setVisible(false);
        tipo='1';//otros servicios
        limpiarCamposProductosServ1();
    }//GEN-LAST:event_rbPagarOtrosServiciosActionPerformed

    private void rbPagarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagarMatriculaActionPerformed
        // TODO add your handling code here:
        jpMatricula.setVisible(true);
        tipo='0';//mensualidad
        limpiarCamposProductosServ();
    }//GEN-LAST:event_rbPagarMatriculaActionPerformed

    private void btnBuscarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaActionPerformed
        // TODO add your handling code here:
        if (rbPagarMatricula.isSelected() && Utils.validarCadena(txtDniAlumno.getText())){
            if(jfPrincipal.menuMatricula==null || jfPrincipal.menuMatricula.isClosed()){
                jfPrincipal.menuMatricula=new jifMatricula(jdp);
                Utils.visualizarInternalFrame(jfPrincipal.menuMatricula, jdp);
            }
            jfPrincipal.menuMatricula.permiteSelFila=0;
            jfPrincipal.menuMatricula.dniAlumno=txtDniAlumno.getText();
            jfPrincipal.menuMatricula.listarMatriculas(paginaActual, tamanioPagina);
            jfPrincipal.menuMatricula.toFront();
        }
    }//GEN-LAST:event_btnBuscarMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcionesPago;
    private javax.swing.JButton btnAgregarConcepto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarConcepto;
    private javax.swing.JButton btnBuscarMatricula;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnQuitarConcepto;
    private javax.swing.JButton btnVerPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox jcbTipoConsulta;
    private javax.swing.JComboBox jcbTipoCpbte;
    private com.toedter.calendar.JDateChooser jdchFechaPago;
    private javax.swing.JPanel jpMatricula;
    private javax.swing.JScrollPane jspTblItemsConceptos;
    private javax.swing.JLabel lblFotoAlumno;
    private javax.swing.JRadioButton rbPagarMatricula;
    private javax.swing.JRadioButton rbPagarOtrosServicios;
    private javax.swing.JTable tblItemsConceptos;
    private javax.swing.JTextField txtApellidosAlumno;
    public static javax.swing.JTextField txtCodConceptoPago;
    public static javax.swing.JTextField txtConceptoPago;
    private javax.swing.JTextField txtCorrelativo;
    private javax.swing.JTextField txtDatoBusqueda;
    public static javax.swing.JTextField txtDetallesMatricula;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtDniPadre;
    public static javax.swing.JTextField txtIdMatricula;
    private javax.swing.JTextField txtNombresAlumno;
    private javax.swing.JTextField txtNombresApellidosPadre;
    private javax.swing.JTextField txtPagoEfectivo;
    private javax.swing.JTextField txtPagoPlin;
    private javax.swing.JTextField txtPagoYape;
    public static javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotalPago;
    // End of variables declaration//GEN-END:variables

    private boolean validarConceptoAgregado(){
        boolean esCorrecto = Utils.validarCadena(txtCodConceptoPago.getText());
        if(!esCorrecto){
            Utils.mensajeError("No se ha cargado aun, el concepto de pago.!!");
        }
        return esCorrecto;
    }

    private void mostrarDatosAlumno(Alumno alumno, Padre padre) {
        txtApellidosAlumno.setText(alumno.getApellidoAlumno());
        txtNombresAlumno.setText(alumno.getNombreAlumno());
        txtDniAlumno.setText(alumno.getDniAlumno());
        txtNombresApellidosPadre.setText(padre.getApellidoPadre() + " " + padre.getNombrePadre());
        txtDniPadre.setText(padre.getDniPadre());
        try {
            if (alumno.getFoto() != null) {
                Image image = Imagen.abrirImagen(alumno.getFoto());
                Utils.cargarImagenEnLabel(image, lblFotoAlumno);
            } else {
                ImageIcon imageIcon = new ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/noDisponible.png"));
                Utils.cargarImagenEnLabel(imageIcon.getImage(), lblFotoAlumno);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void mostrarDatosPadre(String dni) {
        try {
            Padre padre = padreFacade.findPadreByDni(dni);
            if (padre != null) {
                Alumno alumno = alumnoFacade.findAlumnoByIdPadre(padre.getIdPadre());
                if (alumno != null) {
                    mostrarDatosAlumno(alumno, padre);
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void mostrarDatosAlumno(String dni){
        Alumno alumno = alumnoFacade.findAlumnoByDni(dni);
        if (alumno!= null){
            mostrarDatosAlumno(alumno, alumno.getPadre());
        }
    }

    private void mostrarDatosPersona(String dni) {
        if(jcbTipoConsulta.getSelectedIndex()==1){
            mostrarDatosPadre(dni);
        } else if (jcbTipoConsulta.getSelectedIndex()==0){
            mostrarDatosAlumno(dni);
        }
    }

    private void limpiarCamposBusquedaPersona() {
        txtApellidosAlumno.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombresAlumno.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtNombresApellidosPadre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtDniPadre.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtDatoBusqueda.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void limpiarCamposProductosServ(){
        txtCodConceptoPago.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtConceptoPago.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtPrecio.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void limpiarCamposProductosServ1(){
        txtIdMatricula.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtDetallesMatricula.setText(LiteralesTexto.LITERAL_CADENA_VACIA);

    }

    private void activarBotonProcesoPago(){
        if (tblItemsConceptos.getRowCount() > 0) {
            btnPagar.setEnabled(true);
            btnQuitarConcepto.setEnabled(true);
        } else {
            btnPagar.setEnabled(false);
            btnQuitarConcepto.setEnabled(false);
        }
    }

    private void actualizarTotalAPagar(){
        txtTotalPago.setText(totalAPagar.toString());
    }
}
