/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCategorias.java
 *
 * Created on 02/08/2024, 02:42:40 PM
 */
package academiafulbito.vista.interfaces;

import academiafulbito.controlador.beans.ProfesorFacade;
import academiafulbito.modelo.entidades.Profesor;
import academiafulbito.modelo.enums.Estado;
import academiafulbito.vista.utilidades.ButtonEditor;
import academiafulbito.vista.utilidades.ButtonRenderer;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter Jair
 */
public class jifProfesores extends javax.swing.JInternalFrame {

    JDesktopPane jdp;
    public static ProfesorFacade profesorFacade;
    DefaultTableModel modelo;
    String[] nombreColumnas = {"ID", "Nombre", "Apellido", "Telefono", LiteralesTexto.LITERAL_VER, LiteralesTexto.LITERAL_EDITAR, LiteralesTexto.LITERAL_ELIMINAR};
    int indicador;//para saber si estamos en modo de edicion

    /** Creates new form jifCategorias */
    public jifProfesores(JDesktopPane jdpModAF) {
        initComponents();
        jdp = jdpModAF;
        profesorFacade = new ProfesorFacade();
        listarProfesores(profesorFacade.getListadoProfesores());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tphProfesores = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspCategorias = new javax.swing.JScrollPane();
        tblProfesores = new javax.swing.JTable();
        btnNuevoProfesor = new org.edisoncor.gui.button.ButtonRound();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtApellido = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtTelefono = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnGuardar = new org.edisoncor.gui.button.ButtonRound();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(135, 135, 246));
        setClosable(true);
        setTitle("MANTENIMIENTO PROFESORES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphProfesores.setFont(new java.awt.Font("Bookman Old Style", 1, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspCategorias.setBackground(new java.awt.Color(255, 255, 255));
        jspCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspCategorias.setOpaque(false);

        tblProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProfesores.setOpaque(false);
        jspCategorias.setViewportView(tblProfesores);

        jPanel1.add(jspCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 250));

        btnNuevoProfesor.setBackground(new java.awt.Color(156, 156, 247));
        btnNuevoProfesor.setText("+ PROFESOR");
        btnNuevoProfesor.setFont(new java.awt.Font("Arial", 1, 18));
        btnNuevoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProfesorActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 50));

        tphProfesores.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setEditable(false);
        txtNombre.setDescripcion("Nombre*");
        txtNombre.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 720, 40));

        txtApellido.setEditable(false);
        txtApellido.setDescripcion("Apellidos*");
        txtApellido.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 720, 40));

        txtTelefono.setEditable(false);
        txtTelefono.setDescripcion("Telefono*");
        txtTelefono.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 720, 40));

        btnGuardar.setBackground(new java.awt.Color(156, 156, 247));
        btnGuardar.setBorder(null);
        btnGuardar.setText("AÑADIR");
        btnGuardar.setBorderPainted(true);
        btnGuardar.setContentAreaFilled(true);
        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 265, 170, 70));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO PROFESOR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 250, 20));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 220, 70));

        tphProfesores.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProfesorActionPerformed
        // TODO add your handling code here:
        indicador = 0;//para poder guardar
        tphProfesores.setSelectedIndex(1);
        limpiarCampos();
        habilitarCampos(true);
    }//GEN-LAST:event_btnNuevoProfesorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (Utils.mensajeConfirmacion(LiteralesTexto.ESTA_SEGURO_GUARDAR_NUEVO_REGISTRO) == JOptionPane.YES_OPTION) {
            Profesor profesor = getDatosProfesor();
            switch (indicador) {
                case 0://registrar categoria
                    profesorFacade.guardarProfesor(profesor);
                    Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                    break;
                case 1://actualizar categoria
                    break;
            }

            listarProfesores(profesorFacade.getListadoProfesores());
            limpiarCampos();
            habilitarCampos(false);
            indicador = 0;
            tphProfesores.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        habilitarCampos(false);
        tphProfesores.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private org.edisoncor.gui.button.ButtonRound btnGuardar;
    private org.edisoncor.gui.button.ButtonRound btnNuevoProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jspCategorias;
    private javax.swing.JTable tblProfesores;
    private javax.swing.JTabbedPane tphProfesores;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtApellido;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtNombre;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void listarProfesores(List<Profesor> listaProfesores) {
        // Selecciona el primer tab en un JTabbedPane
        tphProfesores.setSelectedIndex(0);

        modelo = Utils.generarModeloTabla(nombreColumnas);

        // Asignar el modelo a la tabla
        tblProfesores.setModel(modelo);

        int[] anchoColumnas = {15, 60, 20, 20, 20, 30, 30}; // Anchos específicos para cada columna
        Utils.setAnchoColumnas(tblProfesores, anchoColumnas);
        Utils.ocultarColumnas(tblProfesores, 0);

        // limpia los datos existentes en la tabla.
        Utils.limpiarModeloTabla(modelo, tblProfesores);

        // Verificar si la lista de socios tiene elementos
        if (listaProfesores.size() > 0) {
            System.out.println("LISTADO DE PROFESORES DESDE LA BBDD");
            // Iterar sobre la lista de categorias y agregar cada categoria a la tabla
            for (Profesor profesor : listaProfesores) {

                System.out.println("profesor.getIdProfesor():" + profesor.getIdProfesor() + " ,profesor.getNombreProfesor():" + profesor.getNombreProfesor() + " ,profesor.getApellidoProfesor():" + profesor.getApellidoProfesor() + " ,profesor.getTelefono():" + profesor.getTelefono());

                // Crea un array de objetos con los datos de la categoria para agregar a la tabla.
                Object[] fila = new Object[]{
                    profesor.getIdProfesor(),
                    profesor.getNombreProfesor(),
                    profesor.getApellidoProfesor(),
                    profesor.getTelefono(),
                    LiteralesTexto.LITERAL_VER,
                    LiteralesTexto.LITERAL_EDITAR,
                    LiteralesTexto.LITERAL_ELIMINAR
                };
                modelo.addRow(fila); // Agregar la fila al modelo de la tabla
            }
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblProfesores.setDefaultRenderer(Object.class, new Utils(18));

            // Establece el modo de selección de filas para permitir solo una selección a la vez.
            tblProfesores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            tblProfesores.setOpaque(false); // Hace la tabla transparente
            ((DefaultTableCellRenderer) tblProfesores.getDefaultRenderer(Object.class)).setOpaque(false); // Hace las celdas transparentes
            tblProfesores.setShowGrid(false); // Desactiva el grid para ocultar los bordes predeterminados
            tblProfesores.setIntercellSpacing(new Dimension(0, 0)); // Elimina el espacio entre celdas
            jspCategorias.getViewport().setOpaque(false); // Hace el viewport transparente

            // Agregar boton ver
            tblProfesores.getColumn(LiteralesTexto.LITERAL_VER).setCellRenderer(new ButtonRenderer(LiteralesTexto.LITERAL_VER));
            tblProfesores.getColumn(LiteralesTexto.LITERAL_VER).setCellEditor(new ButtonEditor(LiteralesTexto.LITERAL_VER));

            // Agregar boton Editar
            tblProfesores.getColumn(LiteralesTexto.LITERAL_EDITAR).setCellRenderer(new ButtonRenderer(LiteralesTexto.LITERAL_EDITAR));
            tblProfesores.getColumn(LiteralesTexto.LITERAL_EDITAR).setCellEditor(new ButtonEditor(LiteralesTexto.LITERAL_EDITAR));

            // Agregar boton Eliminar
            tblProfesores.getColumn(LiteralesTexto.LITERAL_ELIMINAR).setCellRenderer(new ButtonRenderer(LiteralesTexto.LITERAL_ELIMINAR));
            tblProfesores.getColumn(LiteralesTexto.LITERAL_ELIMINAR).setCellEditor(new ButtonEditor(LiteralesTexto.LITERAL_ELIMINAR));

        }
    }

    private Profesor getDatosProfesor() {
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String telefono = txtTelefono.getText();

        return new Profesor(nombre, apellido, telefono);
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
    }

    private void habilitarCampos(boolean band) {
        txtNombre.setEditable(band);
        txtApellido.setEditable(band);
        txtTelefono.setEditable(band);
    }
}
