/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCanchas.java
 *
 * Created on 02/08/2024, 02:42:40 PM
 */

package academiafulbito.vista.interfaces;

import academiafulbito.controlador.beans.CanchaFacade;
import academiafulbito.controlador.beans.LugarEntrenamientoFacade;
import academiafulbito.controlador.beans.ProductoServicioFacade;
import academiafulbito.modelo.entidades.Cancha;
import academiafulbito.modelo.entidades.ProductoServicio;
import academiafulbito.modelo.enums.Estado;
import academiafulbito.vista.reportes.Reportes;
import academiafulbito.vista.utilidades.DialogUtils;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronald J
 */
public class jifProductoServicios extends javax.swing.JInternalFrame {

    JDesktopPane jDesktopPane;

    int indicador;//para saber si estamos en modo de edicion
    private int idSeleccionada; // Variable para almacenar la ID de la cancha seleccionada
    private int paginaActual = 1;
    private int tamanioPagina = 5;//para el paginado de tabla
    private int totalPaginas;

    public static ProductoServicioFacade productoServicioFacade;
    DefaultTableModel modelo;
    String[] nombreColumnas = {
        LiteralesTexto.LITERAL_ID,//0
        LiteralesTexto.LITERAL_NOMBRE_PRODUCTO,//1
        LiteralesTexto.LITERAL_DESCRIPCION,//2
        LiteralesTexto.LITERAL_PRECIO,//3
        LiteralesTexto.LITERAL_STOCK,//4
        LiteralesTexto.LITERAL_ID_CATEGORIAPROD,//5
        LiteralesTexto.LITERAL_ESTADO,//6
        LiteralesTexto.LITERAL_VER,
        LiteralesTexto.LITERAL_EDITAR,
        LiteralesTexto.LITERAL_ELIMINAR
    };
    public static int permiteSelFila = -1;//este valor no permite seleccionar la fila en la tabla
    /** Creates new form jifCanchas */
    public jifProductoServicios(JDesktopPane jdpModAF){
        initComponents();
        jDesktopPane = jdpModAF;
        //Utils.cargarComboEstado(jcbEstado);
        accionBotones(false, false, false);
      
        productoServicioFacade = new ProductoServicioFacade();
        listarProductoServicio(paginaActual, tamanioPagina);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tphProductoServicio = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspCanchas = new javax.swing.JScrollPane();
        tblProductoServicio = new javax.swing.JTable();
        lblPaginaActual = new javax.swing.JLabel();
        btnAnterior = new org.edisoncor.gui.button.ButtonRound();
        btnSiguiente = new org.edisoncor.gui.button.ButtonRound();
        btnNuevoHorario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCategoriaProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdCategoriaProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnBucarCategoriaProducto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombreProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdProductoServicio = new org.edisoncor.gui.textField.TextField();
        btnImprimir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtDescripcionProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtPrecio = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtStock = new org.edisoncor.gui.textField.TextFieldRoundBackground();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setTitle("MANTENIMIENTO PRODUCTO SERVICIO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphProductoServicio.setFont(new java.awt.Font("Bookman Old Style", 1, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspCanchas.setBackground(new java.awt.Color(255, 255, 255));
        jspCanchas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspCanchas.setOpaque(false);

        tblProductoServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProductoServicio.setOpaque(false);
        tblProductoServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoServicioMouseClicked(evt);
            }
        });
        jspCanchas.setViewportView(tblProductoServicio);

        jPanel1.add(jspCanchas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1110, 270));

        lblPaginaActual.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        lblPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaginaActual.setText("10");
        jPanel1.add(lblPaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 220, 50));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior.setText("<<");
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 24));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, 50));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText(">>");
        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 24));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 420, -1, 50));

        btnNuevoHorario.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnNuevoHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/nuevo.png"))); // NOI18N
        btnNuevoHorario.setText("<html><center>NUEVA<br>CANCHA</center></html>");
        btnNuevoHorario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNuevoHorario.setContentAreaFilled(false);
        btnNuevoHorario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoHorario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 180, 120));

        tphProductoServicio.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLabel1.setForeground(new java.awt.Color(103, 98, 98));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO PRODUCTO SERVICIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 410, 20));

        txtCategoriaProducto.setEditable(false);
        txtCategoriaProducto.setDescripcion("Categoria Producto*");
        txtCategoriaProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtCategoriaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCategoriaProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 450, 50));

        txtIdCategoriaProducto.setEditable(false);
        txtIdCategoriaProducto.setDescripcion("Id*");
        txtIdCategoriaProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtIdCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 110, 50));

        btnBucarCategoriaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/lupa.png"))); // NOI18N
        btnBucarCategoriaProducto.setBorderPainted(false);
        btnBucarCategoriaProducto.setContentAreaFilled(false);
        btnBucarCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBucarCategoriaProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBucarCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 80, 60));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 190, 70));

        txtNombreProducto.setEditable(false);
        txtNombreProducto.setDescripcion("Nombre*");
        txtNombreProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 570, 50));
        jPanel2.add(txtIdProductoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));
        txtIdProductoServicio.setVisible(false);

        btnImprimir.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/reportes.png"))); // NOI18N
        btnImprimir.setText("REPORTE");
        btnImprimir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 190, -1));

        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/guardar-datos.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 190, 70));

        txtDescripcionProducto.setEditable(false);
        txtDescripcionProducto.setDescripcion("Descripcion*");
        txtDescripcionProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 570, 50));

        txtPrecio.setEditable(false);
        txtPrecio.setDescripcion("Precio*");
        txtPrecio.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 570, 50));

        txtStock.setEditable(false);
        txtStock.setDescripcion("Stock*");
        txtStock.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 570, 50));

        tphProductoServicio.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphProductoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            listarProductoServicio(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
            listarProductoServicio(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtCategoriaProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaProductoKeyTyped
     
}//GEN-LAST:event_txtCategoriaProductoKeyTyped

    private void btnBucarCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBucarCategoriaProductoActionPerformed
     
}//GEN-LAST:event_btnBucarCategoriaProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       
}//GEN-LAST:event_btnCancelarActionPerformed

    private void tblProductoServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoServicioMouseClicked
        // TODO add your handling code here:
         switch(permiteSelFila){
            case 0://permite llamarlo desde una ventana externa
                int nroFila = tblProductoServicio.getSelectedRow();
                if(nroFila != -1){
                    int codProductoServicio=Integer.parseInt(tblProductoServicio.getValueAt(nroFila, 0).toString());
                    ProductoServicio unProductoServicio=productoServicioFacade.findProductoServicioById(codProductoServicio);
                    jfPrincipal.menuPagos.txtCodConceptoPago.setText(""+codProductoServicio);
                    jfPrincipal.menuPagos.txtConceptoPago.setText(tblProductoServicio.getValueAt(nroFila, 1).toString());
                    jfPrincipal.menuPagos.txtPrecio.setText(tblProductoServicio.getValueAt(nroFila, 3).toString());
                    jfPrincipal.menuPagos.productoServicio=unProductoServicio;

                }
                try{
                    setClosed(true);
                }catch(Exception ex){
                    ex.printStackTrace();
                }
                break;
        }
   
    }//GEN-LAST:event_tblProductoServicioMouseClicked


    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
      

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHorarioActionPerformed
       
}//GEN-LAST:event_btnNuevoHorarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnAnterior;
    private javax.swing.JButton btnBucarCategoriaProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevoHorario;
    private org.edisoncor.gui.button.ButtonRound btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jspCanchas;
    private javax.swing.JLabel lblPaginaActual;
    private javax.swing.JTable tblProductoServicio;
    private javax.swing.JTabbedPane tphProductoServicio;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtCategoriaProducto;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtDescripcionProducto;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdCategoriaProducto;
    private org.edisoncor.gui.textField.TextField txtIdProductoServicio;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtNombreProducto;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtPrecio;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtStock;
    // End of variables declaration//GEN-END:variables

    private void listarProductoServicio(List<ProductoServicio> listaProductoServicio){
        // Selecciona el primer tab en un JTabbedPane
        tphProductoServicio.setSelectedIndex(0);

        modelo = Utils.generarModeloTabla(nombreColumnas);

        // Asignar el modelo a la tabla
        tblProductoServicio.setModel(modelo);

        int[] anchoColumnas = {15,45,40, 25, 30, 50, 20, 15, 25, 25}; // Anchos específicos para cada columna
        Utils.setAnchoColumnas(tblProductoServicio, anchoColumnas);
        Utils.ocultarColumnas(tblProductoServicio, 0);//ocultar la primera columna
        Utils.ocultarColumnas(tblProductoServicio, 5);//ocultar la primera columna
        Utils.ocultarColumnas(tblProductoServicio, 6);//ocultar columna estado

        // limpia los datos existentes en la tabla.
        Utils.limpiarModeloTabla(modelo, tblProductoServicio);

        // Verificar si la lista de socios tiene elementos
        if (listaProductoServicio.size() > 0) {

            // Iterar sobre la lista de canchas y agregar cada cancha a la tabla
            for (ProductoServicio productoServicio : listaProductoServicio) {

                // Crea un array de objetos con los datos de la cancha para agregar a la tabla.
                Object[] fila = new Object[]{
                    productoServicio.getIdProducto(),
                    productoServicio.getNombreProducto(),
                    productoServicio.getDescripcion(),
                    productoServicio.getPrecio(),
                    productoServicio.getStock(),
                    productoServicio.getCategoriaProducto().getIdCategoriaProd(),
                    productoServicio.getEstado(),
                    LiteralesTexto.LITERAL_VER,
                    LiteralesTexto.LITERAL_EDITAR,
                    LiteralesTexto.LITERAL_ELIMINAR
                };
                modelo.addRow(fila); // Agregar la fila al modelo de la tabla
            }
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblProductoServicio.setDefaultRenderer(Object.class, new Utils(14));

            // Establece el modo de selección de filas para permitir solo una selección a la vez.
            tblProductoServicio.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            Utils.configurarEstiloTabla(tblProductoServicio, jspCanchas);
            Utils.configurarBotonesAccion(tblProductoServicio);
        }
    }

    private void accionBotones(boolean d, boolean e, boolean f) {
        btnCancelar.setEnabled(d);
        btnGuardar.setEnabled(e);
        btnImprimir.setEnabled(f);
    }

    private void listarProductoServicio(int paginaActual, int tamanioPagina) {
        totalPaginas = productoServicioFacade.obtenerTotalPaginas(tamanioPagina);

        List<ProductoServicio> listaProductoServicio = productoServicioFacade.listarEntidadesPaginadas(paginaActual, tamanioPagina);

        // Actualizar el JLabel con la página actual
        lblPaginaActual.setText("Página " + paginaActual + " de " + totalPaginas);

        // Mostrar las canchas en la tabla
        listarProductoServicio(listaProductoServicio);
        actualizarEstadoBotones();// Actualizar el estado de los botones

    }

    private void actualizarEstadoBotones() {
        btnAnterior.setEnabled(paginaActual > 1);
        btnSiguiente.setEnabled(paginaActual < totalPaginas);
    }

    private void limpiarCampos() {
        txtNombreProducto.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtIdCategoriaProducto.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtCategoriaProducto.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void habilitarCampos(boolean band) {
        txtNombreProducto.setEditable(band);
        txtIdCategoriaProducto.setEditable(band);
        txtCategoriaProducto.setEditable(band);
        
    }


    public void cargarDatosEnFormulario(int row) {

    }

    private ProductoServicio getDatosProductoServicio(ProductoServicio productoServicio) {

        productoServicio.setNombreProducto(txtNombreProducto.getText());
        productoServicio.setDescripcion(txtDescripcionProducto.getText());
        
        double precioDouble = Double.parseDouble(txtPrecio.getText());
        BigDecimal precio = BigDecimal.valueOf(precioDouble);
        productoServicio.setPrecio(precio);

        int stock = Integer.parseInt(txtStock.getText());
        productoServicio.setStock(stock);

     



        return productoServicio;

    }


}