/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCanchas.java
 *
 * Created on 02/08/2024, 02:42:40 PM
 */

package academiafulbito.vista.interfaces;

import academiafulbito.controlador.beans.CanchaFacade;
import academiafulbito.controlador.beans.CategoriaProductoFacade;
import academiafulbito.controlador.beans.LugarEntrenamientoFacade;
import academiafulbito.controlador.beans.ProductoServicioFacade;
import academiafulbito.modelo.entidades.Cancha;
import academiafulbito.modelo.entidades.CategoriaProducto;
import academiafulbito.modelo.entidades.ProductoServicio;
import academiafulbito.modelo.enums.Estado;
import academiafulbito.vista.reportes.Reportes;
import academiafulbito.vista.utilidades.DialogUtils;
import academiafulbito.vista.utilidades.LiteralesTexto;
import academiafulbito.vista.utilidades.Utils;
import groovyjarjarcommonscli.ParseException;
import java.awt.Cursor;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronald J
 */
public class jifProductoServicios extends javax.swing.JInternalFrame {

    JDesktopPane jdp;

    int indicador;//para saber si estamos en modo de edicion
    private int idSeleccionada; // Variable para almacenar la ID de la cancha seleccionada
    private int paginaActual = 1;
    private int tamanioPagina = 5;//para el paginado de tabla
    private int totalPaginas;
    public char tipo;

    public static ProductoServicioFacade productoServicioFacade;
    public static CategoriaProductoFacade categoriaProductoFacade;
    DefaultTableModel modelo;
    String[] nombreColumnas = {
        LiteralesTexto.LITERAL_ID,//0
        LiteralesTexto.LITERAL_NOMBRE_PRODUCTO,//1
        LiteralesTexto.LITERAL_DESCRIPCION,//2
        LiteralesTexto.LITERAL_PRECIO,//3
        LiteralesTexto.LITERAL_STOCK,//4
        LiteralesTexto.LITERAL_ID_CATEGORIAPROD,//5
        LiteralesTexto.LITERAL_NOMBRE_CATPRO,//6
        LiteralesTexto.LITERAL_ESTADO,//7
        LiteralesTexto.LITERAL_TIPO_PRODUCTO,//8
        LiteralesTexto.LITERAL_VER,
        LiteralesTexto.LITERAL_EDITAR,
        LiteralesTexto.LITERAL_ELIMINAR
    };
    public static int permiteSelFila = -1;//este valor no permite seleccionar la fila en la tabla
    /** Creates new form jifCanchas */
    public jifProductoServicios(JDesktopPane jdpModAF){
        initComponents();
        jdp = jdpModAF;
        permiteSelFila=-1;
        Utils.cargarComboEstado(jcbEstado);
        accionBotones(false, false, false);
      
        productoServicioFacade = new ProductoServicioFacade();
        categoriaProductoFacade = new CategoriaProductoFacade();
        listarProductoServicio(paginaActual, tamanioPagina);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoProducto = new javax.swing.ButtonGroup();
        tphProductoServicio = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspProductoServicios = new javax.swing.JScrollPane();
        tblProductoServicio = new javax.swing.JTable();
        lblPaginaActual = new javax.swing.JLabel();
        btnAnterior = new org.edisoncor.gui.button.ButtonRound();
        btnSiguiente = new org.edisoncor.gui.button.ButtonRound();
        btnNuevoProductoServicio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCategoriaProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdCategoriaProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        btnBucarCategoriaProducto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombreProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtIdProductoServicio = new org.edisoncor.gui.textField.TextField();
        btnImprimir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtDescripcionProducto = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtPrecio = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtStock = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jcbEstado = new org.edisoncor.gui.comboBox.ComboBoxRound();
        rbMensualidades = new javax.swing.JRadioButton();
        rbOtrosServicios = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setTitle("MANTENIMIENTO PRODUCTO SERVICIO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tphProductoServicio.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jspProductoServicios.setBackground(new java.awt.Color(255, 255, 255));
        jspProductoServicios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspProductoServicios.setOpaque(false);

        tblProductoServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProductoServicio.setOpaque(false);
        tblProductoServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoServicioMouseClicked(evt);
            }
        });
        tblProductoServicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblProductoServicioMouseMoved(evt);
            }
        });
        jspProductoServicios.setViewportView(tblProductoServicio);

        jPanel1.add(jspProductoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1110, 270));

        lblPaginaActual.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        lblPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaginaActual.setText("10");
        jPanel1.add(lblPaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 220, 50));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior.setText("<<");
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 24));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, 50));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText(">>");
        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 24));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 420, -1, 50));

        btnNuevoProductoServicio.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnNuevoProductoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/nuevo.png"))); // NOI18N
        btnNuevoProductoServicio.setText("<html><center>NUEVO<br>PRODSERVICIO</center></html>");
        btnNuevoProductoServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNuevoProductoServicio.setContentAreaFilled(false);
        btnNuevoProductoServicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoProductoServicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoProductoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoServicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoProductoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 180, 120));

        tphProductoServicio.addTab("LISTADO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLabel1.setForeground(new java.awt.Color(103, 98, 98));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO PRODUCTO SERVICIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 410, 20));

        txtCategoriaProducto.setEditable(false);
        txtCategoriaProducto.setDescripcion("Categoria Producto*");
        txtCategoriaProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        txtCategoriaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCategoriaProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 450, 50));

        txtIdCategoriaProducto.setEditable(false);
        txtIdCategoriaProducto.setDescripcion("Id*");
        txtIdCategoriaProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtIdCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 110, 50));

        btnBucarCategoriaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/lupa.png"))); // NOI18N
        btnBucarCategoriaProducto.setBorderPainted(false);
        btnBucarCategoriaProducto.setContentAreaFilled(false);
        btnBucarCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBucarCategoriaProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBucarCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 80, 60));

        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/volver.png"))); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 190, 70));

        txtNombreProducto.setEditable(false);
        txtNombreProducto.setDescripcion("Nombre*");
        txtNombreProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 570, 50));
        jPanel2.add(txtIdProductoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));
        txtIdProductoServicio.setVisible(false);

        btnImprimir.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/reportes.png"))); // NOI18N
        btnImprimir.setText("REPORTE");
        btnImprimir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 190, -1));

        btnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academiafulbito/vista/imagenes/guardar-datos.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 190, 70));

        txtDescripcionProducto.setEditable(false);
        txtDescripcionProducto.setDescripcion("Descripcion*");
        txtDescripcionProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 570, 50));

        txtPrecio.setEditable(false);
        txtPrecio.setDescripcion("Precio*");
        txtPrecio.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 570, 50));

        txtStock.setEditable(false);
        txtStock.setDescripcion("Stock*");
        txtStock.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 570, 50));

        jcbEstado.setEnabled(false);
        jcbEstado.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 220, 40));

        bgTipoProducto.add(rbMensualidades);
        rbMensualidades.setText("MENSUALIDADES");
        jPanel2.add(rbMensualidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 120, -1));

        bgTipoProducto.add(rbOtrosServicios);
        rbOtrosServicios.setText("OTROS SERVICIOS");
        jPanel2.add(rbOtrosServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        tphProductoServicio.addTab("REGISTRO", jPanel2);

        getContentPane().add(tphProductoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            listarProductoServicio(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
            listarProductoServicio(paginaActual, tamanioPagina);
        }
}//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtCategoriaProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaProductoKeyTyped
     
}//GEN-LAST:event_txtCategoriaProductoKeyTyped

    private void btnBucarCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBucarCategoriaProductoActionPerformed
      if(jfPrincipal.menuCategoriaProducto == null || jfPrincipal.menuCategoriaProducto.isClosed()){
            jfPrincipal.menuCategoriaProducto = new jifCategoriaProducto(jdp);
            Utils.visualizarInternalFrame(jfPrincipal.menuCategoriaProducto, jdp);
        }
        jfPrincipal.menuCategoriaProducto.permiteSelFila=0;//este valor permite seleccionar con un clic en la fila de la tabla de padres
        jfPrincipal.menuCategoriaProducto.toFront();
}//GEN-LAST:event_btnBucarCategoriaProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       
}//GEN-LAST:event_btnCancelarActionPerformed

    private void tblProductoServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoServicioMouseClicked
        // TODO add your handling code here:
         switch(permiteSelFila){
            case 0://permite llamarlo desde una ventana externa
                int nroFila = tblProductoServicio.getSelectedRow();
                if(nroFila != -1){
                    int codProductoServicio=Integer.parseInt(tblProductoServicio.getValueAt(nroFila, 0).toString());
                    ProductoServicio unProductoServicio=productoServicioFacade.findProductoServicioById(codProductoServicio);
                    jfPrincipal.menuPagos.txtCodConceptoPago.setText(""+codProductoServicio);
                    jfPrincipal.menuPagos.txtConceptoPago.setText(tblProductoServicio.getValueAt(nroFila, 1).toString());
                    jfPrincipal.menuPagos.txtPrecio.setText(tblProductoServicio.getValueAt(nroFila, 3).toString());
                    jfPrincipal.menuPagos.productoServicio=unProductoServicio;

                }
                try{
                    setClosed(true);
                }catch(Exception ex){
                    ex.printStackTrace();
                }
                break;
        }
   
    }//GEN-LAST:event_tblProductoServicioMouseClicked


    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
      

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoProductoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoServicioActionPerformed
        indicador = 0;//para poder guardar
        tphProductoServicio.setSelectedIndex(1);
        limpiarCampos();
        habilitarCampos(true);
        accionBotones(true, true,false);
}//GEN-LAST:event_btnNuevoProductoServicioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (validarDatosProductoServicio()) {
                String cadenaMensaje = 0 == indicador ? LiteralesTexto.ESTA_SEGURO_GUARDAR_NUEVO_REGISTRO : LiteralesTexto.ESTA_SEGURO_MODIFICAR_REGISTRO;
                if (Utils.mensajeConfirmacion(cadenaMensaje) == JOptionPane.YES_OPTION) {
                    ProductoServicio productoServicio;
                    switch (indicador) {
                        case 0://registrar categoria
                            productoServicio = new ProductoServicio();
                            productoServicioFacade.guardarProductoServicio(getDatosProductoServicio(productoServicio));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_GUARDADO_CORRECTAMENTE);
                            break;
                        case 1://actualizar categoria
                            productoServicio = productoServicioFacade.findProductoServicioById(idSeleccionada);
                            productoServicioFacade.actualizarProductoServicio(getDatosProductoServicio(productoServicio));
                            Utils.mensajeInformacion(LiteralesTexto.REGISTRO_ACTUALIZADO_CORRECTAMENTE);
                            break;
                    }

                    listarProductoServicio(paginaActual, tamanioPagina);
                    limpiarCampos();
                    habilitarCampos(false);
                    accionBotones(false, false, false);
                    btnGuardar.setText("Añadir");
                    indicador = 0;
                    tphProductoServicio.setSelectedIndex(0);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblProductoServicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoServicioMouseMoved
        // TODO add your handling code here:
        int col = tblProductoServicio.columnAtPoint(evt.getPoint());
        int row = tblProductoServicio.rowAtPoint(evt.getPoint());
        if (col >= 0 && (tblProductoServicio.getColumnName(col).equals(LiteralesTexto.LITERAL_VER) ||
                         tblProductoServicio.getColumnName(col).equals(LiteralesTexto.LITERAL_EDITAR) ||
                         tblProductoServicio.getColumnName(col).equals(LiteralesTexto.LITERAL_ELIMINAR))) {
            tblProductoServicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            tblProductoServicio.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_tblProductoServicioMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoProducto;
    private org.edisoncor.gui.button.ButtonRound btnAnterior;
    private javax.swing.JButton btnBucarCategoriaProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevoProductoServicio;
    private org.edisoncor.gui.button.ButtonRound btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.comboBox.ComboBoxRound jcbEstado;
    private javax.swing.JScrollPane jspProductoServicios;
    private javax.swing.JLabel lblPaginaActual;
    private javax.swing.JRadioButton rbMensualidades;
    private javax.swing.JRadioButton rbOtrosServicios;
    private javax.swing.JTable tblProductoServicio;
    private javax.swing.JTabbedPane tphProductoServicio;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtCategoriaProducto;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtDescripcionProducto;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground txtIdCategoriaProducto;
    private org.edisoncor.gui.textField.TextField txtIdProductoServicio;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtNombreProducto;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtPrecio;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtStock;
    // End of variables declaration//GEN-END:variables

    private void listarProductoServicio(List<ProductoServicio> listaProductoServicio){
        // Selecciona el primer tab en un JTabbedPane
        tphProductoServicio.setSelectedIndex(0);

        modelo = Utils.generarModeloTabla(nombreColumnas);

        // Asignar el modelo a la tabla
        tblProductoServicio.setModel(modelo);

        int[] anchoColumnas = {15,45,40, 25, 30, 50, 20,20,20, 15, 25, 25}; // Anchos específicos para cada columna
        Utils.setAnchoColumnas(tblProductoServicio, anchoColumnas);
        Utils.ocultarColumnas(tblProductoServicio, 0);//ocultar la primera columna
        Utils.ocultarColumnas(tblProductoServicio, 5);//ocultar el id
        Utils.ocultarColumnas(tblProductoServicio, 6);//ocultar el nombre
        Utils.ocultarColumnas(tblProductoServicio, 7);//ocultar columna estado
        Utils.ocultarColumnas(tblProductoServicio, 8);//ocultar columna tipo producto

        // limpia los datos existentes en la tabla.
        Utils.limpiarModeloTabla(modelo, tblProductoServicio);

        // Verificar si la lista de socios tiene elementos
        if (listaProductoServicio.size() > 0) {

            // Iterar sobre la lista de canchas y agregar cada cancha a la tabla
            for (ProductoServicio productoServicio : listaProductoServicio) {

                // Crea un array de objetos con los datos de la cancha para agregar a la tabla.
                Object[] fila = new Object[]{
                    productoServicio.getIdProducto(),
                    productoServicio.getNombreProducto(),
                    productoServicio.getDescripcion(),
                    productoServicio.getPrecio(),
                    productoServicio.getStock(),
                    productoServicio.getCategoriaProducto().getIdCategoriaProd(),
                    productoServicio.getCategoriaProducto().getNombreCategoria(),
                    productoServicio.getEstado(),
                    productoServicio.getTipo_producto(),
                    LiteralesTexto.LITERAL_VER,
                    LiteralesTexto.LITERAL_EDITAR,
                    LiteralesTexto.LITERAL_ELIMINAR
                };
                modelo.addRow(fila); // Agregar la fila al modelo de la tabla
            }
            // Establece un renderizador personalizado para las celdas de la tabla.
            tblProductoServicio.setDefaultRenderer(Object.class, new Utils(14));

            // Establece el modo de selección de filas para permitir solo una selección a la vez.
            tblProductoServicio.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            Utils.configurarEstiloTabla(tblProductoServicio, jspProductoServicios);
            Utils.configurarBotonesAccion(tblProductoServicio);
        }
    }

    private void accionBotones(boolean d, boolean e, boolean f) {
        btnCancelar.setEnabled(d);
        btnGuardar.setEnabled(e);
        btnImprimir.setEnabled(f);
    }

    public void listarProductoServicio(int paginaActual, int tamanioPagina) {
        totalPaginas = productoServicioFacade.obtenerTotalPaginas(tamanioPagina);
        List<ProductoServicio> listaProductoServicio=null;
        if(permiteSelFila==0){
            listaProductoServicio=productoServicioFacade.getListadoProductoServiciosPorTipo(tipo);
        } else {
            listaProductoServicio=productoServicioFacade.listarEntidadesPaginadas(paginaActual, tamanioPagina);
        }
        //List<ProductoServicio> listaProductoServicio = productoServicioFacade.listarEntidadesPaginadas(paginaActual, tamanioPagina);

        // Actualizar el JLabel con la página actual
        lblPaginaActual.setText("Página " + paginaActual + " de " + totalPaginas);

        // Mostrar las canchas en la tabla
        listarProductoServicio(listaProductoServicio);
        actualizarEstadoBotones();// Actualizar el estado de los botones

    }

    private void actualizarEstadoBotones() {
        btnAnterior.setEnabled(paginaActual > 1);
        btnSiguiente.setEnabled(paginaActual < totalPaginas);
    }

    private void limpiarCampos() {
        txtNombreProducto.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtIdCategoriaProducto.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
        txtCategoriaProducto.setText(LiteralesTexto.LITERAL_CADENA_VACIA);
    }

    private void habilitarCampos(boolean band) {
        txtNombreProducto.setEditable(band);
        txtDescripcionProducto.setEditable(band);
        txtPrecio.setEditable(band);
        txtStock.setEditable(band);
        txtIdCategoriaProducto.setEditable(band);
        txtCategoriaProducto.setEditable(band);
        //txtTipoProducto.setEditable(band);
        if (indicador == 0) {
            jcbEstado.setSelectedIndex(0);
            jcbEstado.setEnabled(!band);
        } else {
            jcbEstado.setEnabled(band);
        }
        
    }


    public void cargarDatosEnFormulario(int row) throws ParseException {
       if (row != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblProductoServicio.getValueAt(row, 0).toString()); // Supone que la ID está en la primera columna

            // Obtener los datos de la fila seleccionada
            String nombre = (String) tblProductoServicio.getValueAt(row, 1);
            String descripcion = (String) tblProductoServicio.getValueAt(row, 2);
            double precio = Double.parseDouble(tblProductoServicio.getValueAt(row, 3).toString()); // Cambiar a Double
            int stock = Integer.parseInt(tblProductoServicio.getValueAt(row, 4).toString());
            int idCategoria= Integer.parseInt(tblProductoServicio.getValueAt(row, 5).toString());//5
            String nombreCategoria=(String) tblProductoServicio.getValueAt(row, 6);//6
            Estado estado = (Estado) tblProductoServicio.getValueAt(row, 7);
            Character tipo_producto = (Character) tblProductoServicio.getValueAt(row, 8);


            // Asignar los datos a los JTextField en el segundo panel
            txtNombreProducto.setText(nombre);//11
            txtDescripcionProducto.setText(descripcion);//2
            txtPrecio.setText(String.valueOf(precio));//3
            txtStock.setText(String.valueOf(stock));//4
            txtIdCategoriaProducto.setText(""+idCategoria);//5
            txtCategoriaProducto.setText(nombreCategoria);//6
            //txtTipoProducto.setText(tipo_producto.toString());//8

            // Seleccionar el estado en el JComboBox
            jcbEstado.setSelectedItem(estado);//7
            
            //para el radiobutton
           if (tipo_producto != null) {  // Asegurarse de que tipo_producto no sea null
               if (tipo_producto == '0') {
                   rbMensualidades.setSelected(true);  // Seleccionar rbMensualidades si tipo_producto es '0'
                   rbOtrosServicios.setSelected(false);  // Asegurarse de que el otro no esté seleccionado
               } else if (tipo_producto == '1') {
                   rbOtrosServicios.setSelected(true);  // Seleccionar rbOtrosServicios si tipo_producto es '1'
                   rbMensualidades.setSelected(false);  // Asegurarse de que el otro no esté seleccionado
               } else {
                   // Si tipo_producto tiene un valor inesperado, puedes hacer algo adicional si es necesario
                   rbMensualidades.setSelected(false);
                   rbOtrosServicios.setSelected(false);
               }
           }

            // Cambiar al segundo panel donde están los JTextField
            tphProductoServicio.setSelectedIndex(1);
            btnGuardar.setText("Modificar");
            indicador = 1;
            accionBotones(true, true, true);
            habilitarCampos(true);
        } else {
            //colocar alguna alerta
        }

    }

    private ProductoServicio getDatosProductoServicio(ProductoServicio productoServicio) {

        productoServicio.setNombreProducto(txtNombreProducto.getText());
        productoServicio.setDescripcion(txtDescripcionProducto.getText());
        double precioDouble = Double.parseDouble(txtPrecio.getText());
        BigDecimal precio = BigDecimal.valueOf(precioDouble);
        productoServicio.setPrecio(precio);
        int stock = Integer.parseInt(txtStock.getText());
        productoServicio.setStock(stock);
        productoServicio.setCategoriaProducto(categoriaProductoFacade.findCategoriaProductoById(Integer.parseInt(txtIdCategoriaProducto.getText())));
        productoServicio.setEstado((Estado) jcbEstado.getSelectedItem());
        //productoServicio.setTipo_producto(txtTipoProducto.getText().charAt(0));
        if (rbMensualidades.isSelected()) {
            productoServicio.setTipo_producto('0');  
            tipo = '0'; 
        } else if (rbOtrosServicios.isSelected()) {
            productoServicio.setTipo_producto('1'); 
            tipo = '1';  
        }
        return productoServicio;

    }


    private boolean validarDatosProductoServicio(){
        if(!validarCampo(txtNombreProducto.getText(), LiteralesTexto.ERROR_NOMBRE_CAMPO_VACIO)){
            return false;
        }

        if (!validarCampo(txtDescripcionProducto.getText(), LiteralesTexto.ERROR_NOMBRE_CAMPO_VACIO)) {
            return false;
        }

        return true;
    }

    private boolean validarCampo(String valor, String mensajeError) {
        if (!Utils.validarCadena(valor)) {
            Utils.mensajeError(mensajeError);
            return false;
        }
        return true;
    }

    private void getDatosProductoServicio(int filaSeleccionada){
        // Cambiar al segundo panel donde están los JTextField
        tphProductoServicio.setSelectedIndex(1);

        txtNombreProducto.setText(tblProductoServicio.getValueAt(filaSeleccionada, 1).toString());
        txtDescripcionProducto.setText(tblProductoServicio.getValueAt(filaSeleccionada, 2).toString());
        txtPrecio.setText(tblProductoServicio.getValueAt(filaSeleccionada, 3).toString());
        txtStock.setText(tblProductoServicio.getValueAt(filaSeleccionada, 4).toString());
        //txtTipoProducto.setText(tblProductoServicio.getValueAt(filaSeleccionada, 8).toString());
        
    }

    public void eliminarProductoServicioSeleccionada(int filaSeleccionada) {
        if (filaSeleccionada != -1) {
            // Capturar la ID de la fila seleccionada
            idSeleccionada = Integer.parseInt(tblProductoServicio.getValueAt(filaSeleccionada, 0).toString()); // Supone que la ID está en la primera columna
            if (Utils.mensajeConfirmacion(LiteralesTexto.ESTA_SEGURO_ELIMINAR_REGISTRO) == JOptionPane.YES_OPTION) {
                ProductoServicio productoServicioAEliminar = productoServicioFacade.findProductoServicioById(idSeleccionada);
                if(productoServicioAEliminar != null){
                    try {
                        // Llamar al método para eliminar
                        productoServicioFacade.eliminarProductoServicio(productoServicioAEliminar);
                        JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_ELIMINADO_CORRECTAMENTE);

                        // Actualizar la tabla después de eliminar
                        totalPaginas = categoriaProductoFacade.obtenerTotalPaginas(tamanioPagina);

                        // Verificar si la página actual es mayor que el total de páginas después de la eliminación
                        if (paginaActual > totalPaginas) {
                            paginaActual = totalPaginas; // Ajustar la página actual a la última disponible
                        }

                        // Actualizar la tabla después de eliminar
                        listarProductoServicio(paginaActual, tamanioPagina); // Volver a listar las categorías después de la eliminación

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, LiteralesTexto.ERROR_AL_ELIMINAR_EL_REGISTRO+ " : " + e.getMessage(), LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, LiteralesTexto.REGISTRO_NO_ENCONTRADO_EN_LA_BBDD, LiteralesTexto.LITERAL_ERROR, JOptionPane.ERROR_MESSAGE);
                }

            }
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, LiteralesTexto.POR_FAVOR_SELECCIONE_UNA_REGISTRO_PARA_ELIMINAR);
        }
    }
}